/**
 * The CAD document: everything the drawing state holds beside the raw shapes.
 *
 * Kept as ONE object inside the drawing reducer so a single history snapshot
 * captures layers, annotations, component instances, the project record and
 * sheets together — undo cannot restore geometry while leaving its hatch,
 * dimensions or design basis behind.
 */

import type { Shape } from "@/lib/geometry/types";
import { emptyProject, type BridgeProject } from "@/lib/bridge/project";
import type { ComponentInstance } from "@/lib/components/types";
import { componentRegistry } from "@/lib/components/library";
import { instantiateComponent, type InstanceOutput } from "@/lib/components/instantiate";
import type { ComponentIssue } from "@/lib/components/evaluate";
import { instantiateLayers, layerIdFor } from "./layers";
import type { Annotation, DrawingSettings, Layer } from "./types";
import { DEFAULT_DRAWING_SETTINGS } from "./types";
import type { Sheet } from "./sheet";

export interface ComponentNotice {
  instanceId: string;
  ok: boolean;
  message: string;
  issues: ComponentIssue[];
  at: number;
}

export interface CadDocState {
  settings: DrawingSettings;
  layers: Layer[];
  currentLayerId: string;
  annotations: Annotation[];
  components: ComponentInstance[];
  project: BridgeProject;
  sheets: Sheet[];
  /** The last component edit's outcome — a refusal is reported, never half-applied. */
  componentNotice: ComponentNotice | null;
  /** Revision history for the alteration box. */
  revisions: { rev: string; description: string; date: string }[];
}

export function emptyCadDoc(): CadDocState {
  const layers = instantiateLayers(DEFAULT_DRAWING_SETTINGS.layerStandardId);
  return {
    settings: { ...DEFAULT_DRAWING_SETTINGS },
    layers,
    currentLayerId: layerIdFor(layers, "outline"),
    annotations: [],
    components: [],
    project: emptyProject(),
    sheets: [],
    componentNotice: null,
    revisions: [],
  };
}

export function isComponentShape(s: Shape): boolean {
  return Boolean((s as Shape & { componentInstanceId?: string }).componentInstanceId);
}

export function componentIdOf(s: Shape | Annotation): string | undefined {
  return (s as { componentInstanceId?: string }).componentInstanceId;
}

/** Evaluates one instance against the document. */
export function evaluateInstance(inst: ComponentInstance, doc: Pick<CadDocState, "layers" | "settings">): InstanceOutput | null {
  const def = componentRegistry.get(inst.definitionId);
  if (!def) return null;
  return instantiateComponent(inst, def, componentRegistry, doc.layers, doc.settings);
}

/**
 * Replaces every entity generated by the given instances with a fresh
 * regeneration. Instances not listed are left untouched; entities of
 * instances that no longer exist are removed.
 */
export function regenerateInstances(
  shapes: Shape[],
  doc: CadDocState,
  instanceIds?: string[]
): { shapes: Shape[]; annotations: Annotation[]; outputs: Map<string, InstanceOutput> } {
  const live = new Set(doc.components.map((c) => c.id));
  const targets = new Set(instanceIds ?? doc.components.map((c) => c.id));
  const outputs = new Map<string, InstanceOutput>();
  for (const inst of doc.components) {
    if (!targets.has(inst.id)) continue;
    const out = evaluateInstance(inst, doc);
    if (out) outputs.set(inst.id, out);
  }
  const keep = (id: string | undefined) => !id || (live.has(id) && !targets.has(id));
  const nextShapes = shapes.filter((s) => keep(componentIdOf(s)));
  const nextAnn = doc.annotations.filter((a) => keep(componentIdOf(a)));
  for (const out of outputs.values()) {
    nextShapes.push(...(out.shapes as Shape[]));
    nextAnn.push(...out.annotations);
  }
  return { shapes: nextShapes, annotations: nextAnn, outputs };
}

/** Deterministic, readable instance id: BRIDGE-1, BOX-2 ... */
export function nextInstanceId(doc: CadDocState, semanticType: string): string {
  const base = semanticType.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "") || "COMP";
  let n = 1;
  while (doc.components.some((c) => c.id === `${base}-${n}`)) n++;
  return `${base}-${n}`;
}
