/**
 * The CAD document: everything the drawing state holds beside the raw shapes.
 *
 * Kept as ONE object inside the drawing reducer so a single history snapshot
 * captures layers, annotations, component instances, the project record and
 * sheets together — undo cannot restore geometry while leaving its hatch,
 * dimensions or design basis behind.
 */

import type { Shape } from "@/lib/geometry/types";
import { emptyProject, type BridgeProject } from "@/lib/bridge/project";
import type { ComponentDefinition, ComponentInstance, CustomValue, Relationship } from "@/lib/components/types";
import { COMPONENT_LIBRARY, componentRegistry } from "@/lib/components/library";
import { makeRegistry } from "@/lib/components/instantiate";
import type { ComponentRegistry } from "@/lib/components/evaluate";
import { instantiateComponent, type InstanceOutput } from "@/lib/components/instantiate";
import type { ComponentIssue } from "@/lib/components/evaluate";
import { instantiateLayers, layerIdFor } from "./layers";
import type { Annotation, DrawingSettings, Layer } from "./types";
import { DEFAULT_DRAWING_SETTINGS } from "./types";
import type { Sheet } from "./sheet";

export interface ComponentNotice {
  instanceId: string;
  ok: boolean;
  message: string;
  issues: ComponentIssue[];
  at: number;
}

export interface CadDocState {
  settings: DrawingSettings;
  layers: Layer[];
  currentLayerId: string;
  annotations: Annotation[];
  components: ComponentInstance[];
  project: BridgeProject;
  sheets: Sheet[];
  /** The last component edit's outcome — a refusal is reported, never half-applied. */
  componentNotice: ComponentNotice | null;
  /** Revision history for the alteration box. */
  revisions: { rev: string; description: string; date: string }[];
  /**
   * Components made on this drawing — a drawing turned parametric ("Make
   * parametric"). Same data format as the library; saved with the drawing.
   */
  definitions?: ComponentDefinition[];
  /**
   * Relationships and inputs of the component last turned back into geometry,
   * handed to the next "Make parametric" so they survive an edit of the shape.
   */
  carried?: { relations?: Relationship[]; customValues?: CustomValue[] };
}

export function emptyCadDoc(): CadDocState {
  const layers = instantiateLayers(DEFAULT_DRAWING_SETTINGS.layerStandardId);
  return {
    settings: { ...DEFAULT_DRAWING_SETTINGS },
    layers,
    currentLayerId: layerIdFor(layers, "outline"),
    annotations: [],
    components: [],
    project: emptyProject(),
    sheets: [],
    componentNotice: null,
    revisions: [],
  };
}

export function isComponentShape(s: Shape): boolean {
  return Boolean((s as Shape & { componentInstanceId?: string }).componentInstanceId);
}

export function componentIdOf(s: Shape | Annotation): string | undefined {
  return (s as { componentInstanceId?: string }).componentInstanceId;
}

const registryCache = new WeakMap<ComponentDefinition[], ComponentRegistry>();

/** The library plus the drawing's own components. */
export function registryFor(doc: Pick<CadDocState, "definitions">): ComponentRegistry {
  const own = doc.definitions;
  if (!own || own.length === 0) return componentRegistry;
  let r = registryCache.get(own);
  if (!r) {
    r = makeRegistry([...COMPONENT_LIBRARY, ...own]);
    registryCache.set(own, r);
  }
  return r;
}

/** A definition by id, from the library or the drawing. */
export function definitionFor(doc: Pick<CadDocState, "definitions">, id: string): ComponentDefinition | undefined {
  return registryFor(doc).get(id);
}

/** Evaluates one instance against the document. */
export function evaluateInstance(inst: ComponentInstance, doc: Pick<CadDocState, "layers" | "settings" | "definitions">): InstanceOutput | null {
  const reg = registryFor(doc);
  const def = reg.get(inst.definitionId);
  if (!def) return null;
  return instantiateComponent(inst, def, reg, doc.layers, doc.settings);
}

/**
 * Replaces every entity generated by the given instances with a fresh
 * regeneration. Instances not listed are left untouched; entities of
 * instances that no longer exist are removed.
 */
export function regenerateInstances(
  shapes: Shape[],
  doc: CadDocState,
  instanceIds?: string[]
): { shapes: Shape[]; annotations: Annotation[]; outputs: Map<string, InstanceOutput> } {
  const live = new Set(doc.components.map((c) => c.id));
  const targets = new Set(instanceIds ?? doc.components.map((c) => c.id));
  const outputs = new Map<string, InstanceOutput>();
  for (const inst of doc.components) {
    if (!targets.has(inst.id)) continue;
    const out = evaluateInstance(inst, doc);
    if (out) outputs.set(inst.id, out);
  }
  const keep = (id: string | undefined) => !id || (live.has(id) && !targets.has(id));
  const nextShapes = shapes.filter((s) => keep(componentIdOf(s)));
  const nextAnn = doc.annotations.filter((a) => keep(componentIdOf(a)));
  for (const out of outputs.values()) {
    nextShapes.push(...(out.shapes as Shape[]));
    nextAnn.push(...out.annotations);
  }
  return { shapes: nextShapes, annotations: nextAnn, outputs };
}

/** Deterministic, readable instance id: BRIDGE-1, BOX-2 ... */
export function nextInstanceId(doc: CadDocState, semanticType: string): string {
  const base = semanticType.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_|_$/g, "") || "COMP";
  let n = 1;
  while (doc.components.some((c) => c.id === `${base}-${n}`)) n++;
  return `${base}-${n}`;
}
