/**
 * Canonical Template Catalog (UPCE-MASTER-1.0 §86, §5.6, §43, §44, Gate G5 §76)
 *
 * Conforms 100% to schemas/template.schema.json and TemplateDefinition in lib/parametric/schemaTypes.ts.
 * Includes all 10 canonical templates:
 * 1. single_cell_box_culvert
 * 2. two_cell_box_culvert
 * 3. multi_cell_box_culvert
 * 4. railing_post
 * 5. railing_run
 * 6. rcc_bridge
 * 7. parametric_frame_cutout
 * 8. square_tube_profile
 * 9. chamfered_octagonal_polygon
 * 10. rdso_box_bridge
 */

import { TemplateDefinition } from "../schemaTypes";

export const SINGLE_CELL_BOX_CULVERT_TEMPLATE: TemplateDefinition = {
  id: "single_cell_box_culvert",
  name: "Single-Cell Box Culvert",
  category: "component",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  standardsReference: "IRS Concrete Bridge Code / IRC:SP:13",
  parameters: [
    {
      id: "clear_span",
      name: "clear_span",
      role: "DRIVING",
      type: "LENGTH",
      value: 300,
      unit: "mm",
      min: 100,
      max: 1000,
      step: 10,
      provenance: "UserConstraint",
      semanticTag: "clear_span",
    },
    {
      id: "clear_height",
      name: "clear_height",
      role: "DRIVING",
      type: "LENGTH",
      value: 200,
      unit: "mm",
      min: 100,
      max: 800,
      step: 10,
      provenance: "UserConstraint",
      semanticTag: "clear_height",
    },
    {
      id: "wall_thickness",
      name: "wall_thickness",
      role: "DRIVING",
      type: "LENGTH",
      value: 30,
      unit: "mm",
      min: 10,
      max: 100,
      step: 5,
      provenance: "UserConstraint",
      semanticTag: "wall_thickness",
    },
    {
      id: "haunch_leg",
      name: "haunch_leg",
      role: "DRIVING",
      type: "LENGTH",
      value: 35,
      unit: "mm",
      min: 10,
      max: 80,
      step: 5,
      provenance: "UserConstraint",
      semanticTag: "haunch_leg",
    },
    {
      id: "outer_width",
      name: "outer_width",
      role: "DERIVED",
      type: "LENGTH",
      value: 360,
      unit: "mm",
      expr: "clear_span + (wall_thickness * 2)",
      provenance: "UserFormula",
      semanticTag: "outer_width",
    },
    {
      id: "outer_height",
      name: "outer_height",
      role: "DERIVED",
      type: "LENGTH",
      value: 260,
      unit: "mm",
      expr: "clear_height + (wall_thickness * 2)",
      provenance: "UserFormula",
      semanticTag: "outer_height",
    },
  ],
  expressions: [
    {
      targetParameterId: "outer_width",
      expression: "clear_span + (wall_thickness * 2)",
      dependencies: ["clear_span", "wall_thickness"],
      description: "Total structural culvert width including side walls",
    },
    {
      targetParameterId: "outer_height",
      expression: "clear_height + (wall_thickness * 2)",
      dependencies: ["clear_height", "wall_thickness"],
      description: "Total structural culvert height including top and bottom slabs",
    },
  ],
  geometry: {
    points: [
      { id: "p_tl", x: 0, y: 0 },
      { id: "p_tr", x: 360, y: 0 },
      { id: "p_br", x: 360, y: 260 },
      { id: "p_bl", x: 0, y: 260 },
      { id: "i_top_left", x: 65, y: 30 },
      { id: "i_top_right", x: 295, y: 30 },
      { id: "i_right_top", x: 330, y: 65 },
      { id: "i_right_bottom", x: 330, y: 195 },
      { id: "i_bottom_right", x: 295, y: 230 },
      { id: "i_bottom_left", x: 65, y: 230 },
      { id: "i_left_bottom", x: 30, y: 195 },
      { id: "i_left_top", x: 30, y: 65 },
    ],
    lines: [
      { id: "l_outer_top", p1: "p_tl", p2: "p_tr", semanticRole: "top_slab_outer" },
      { id: "l_outer_right", p1: "p_tr", p2: "p_br", semanticRole: "right_wall_outer" },
      { id: "l_outer_bottom", p1: "p_br", p2: "p_bl", semanticRole: "bottom_slab_outer" },
      { id: "l_outer_left", p1: "p_bl", p2: "p_tl", semanticRole: "left_wall_outer" },
      { id: "l_roof", p1: "i_top_left", p2: "i_top_right", semanticRole: "roof_inner" },
      { id: "l_haunch_tr", p1: "i_top_right", p2: "i_right_top", semanticRole: "haunch_tr" },
      { id: "l_right_wall", p1: "i_right_top", p2: "i_right_bottom", semanticRole: "right_wall_inner" },
      { id: "l_haunch_br", p1: "i_right_bottom", p2: "i_bottom_right", semanticRole: "haunch_br" },
      { id: "l_floor", p1: "i_bottom_right", p2: "i_bottom_left", semanticRole: "floor_inner" },
      { id: "l_haunch_bl", p1: "i_bottom_left", p2: "i_left_bottom", semanticRole: "haunch_bl" },
      { id: "l_left_wall", p1: "i_left_bottom", p2: "i_left_top", semanticRole: "left_wall_inner" },
      { id: "l_haunch_tl", p1: "i_left_top", p2: "i_top_left", semanticRole: "haunch_tl" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    {
      id: "c_h_top",
      kind: "horizontal",
      refs: ["l_outer_top"],
      strength: "hard",
      driving: false,
      provenance: "GeometricFact",
      state: "active",
    },
    {
      id: "c_v_left",
      kind: "vertical",
      refs: ["l_outer_left"],
      strength: "hard",
      driving: false,
      provenance: "GeometricFact",
      state: "active",
    },
    {
      id: "c_outer_width",
      kind: "distance_x",
      refs: ["p_tl", "p_tr"],
      paramRef: "outer_width",
      strength: "driving",
      driving: true,
      provenance: "UserConstraint",
      state: "active",
    },
    {
      id: "c_outer_height",
      kind: "distance_y",
      refs: ["p_tl", "p_bl"],
      paramRef: "outer_height",
      strength: "driving",
      driving: true,
      provenance: "UserConstraint",
      state: "active",
    },
  ],
  ports: [
    {
      id: "port_left",
      kind: "edge",
      localFrame: {
        origin: { x: "0", y: "outer_height / 2" },
        angle: "180",
      },
      direction: "bidirectional",
      length: "outer_height",
    },
    {
      id: "port_right",
      kind: "edge",
      localFrame: {
        origin: { x: "outer_width", y: "outer_height / 2" },
        angle: "0",
      },
      direction: "bidirectional",
      length: "outer_height",
    },
    {
      id: "port_top",
      kind: "edge",
      localFrame: {
        origin: { x: "outer_width / 2", y: "0" },
        angle: "90",
      },
      direction: "out",
      length: "outer_width",
    },
    {
      id: "port_bottom",
      kind: "edge",
      localFrame: {
        origin: { x: "outer_width / 2", y: "outer_height" },
        angle: "270",
      },
      direction: "out",
      length: "outer_width",
    },
  ],
  semantics: [
    {
      id: "sem_culvert_body",
      type: "box_culvert_body",
      faces: ["face_solid"],
      edges: ["l_outer_top", "l_outer_right", "l_outer_bottom", "l_outer_left"],
      children: ["sem_inner_void"],
      params: ["clear_span", "clear_height", "wall_thickness"],
      confirmedBy: "author",
    },
    {
      id: "sem_inner_void",
      type: "culvert_cell_void",
      faces: ["face_void"],
      edges: [
        "l_roof",
        "l_haunch_tr",
        "l_right_wall",
        "l_haunch_br",
        "l_floor",
        "l_haunch_bl",
        "l_left_wall",
        "l_haunch_tl",
      ],
      parent: "sem_culvert_body",
      children: [],
      params: ["haunch_leg"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_span_haunch",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "clear_span > (haunch_leg * 2)",
      message: "Clear span must exceed double the haunch leg length to retain open roof",
    },
    {
      ruleId: "val_height_haunch",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "clear_height > (haunch_leg * 2)",
      message: "Clear height must exceed double the haunch leg length to retain open wall",
    },
    {
      ruleId: "val_wall_min",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "wall_thickness >= 10",
      message: "Wall thickness cannot be less than 10 mm",
    },
  ],
  provenance: [
    {
      timestamp: "2026-09-09T00:00:00Z",
      action: "template_created",
      author: "UPCE_Core_Team",
      details: { version: "1.0.0" },
    },
  ],
};

export const TWO_CELL_BOX_CULVERT_TEMPLATE: TemplateDefinition = {
  id: "two_cell_box_culvert",
  name: "Two-Cell Multi-Span Box Culvert",
  category: "bridge",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  standardsReference: "IRS Concrete Bridge Code / RDSO GAD 2-Span",
  parameters: [
    {
      id: "bay1_span",
      name: "bay1_span",
      role: "DRIVING",
      type: "LENGTH",
      value: 250,
      unit: "mm",
      min: 100,
      max: 800,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "bay2_span",
      name: "bay2_span",
      role: "DRIVING",
      type: "LENGTH",
      value: 250,
      unit: "mm",
      min: 100,
      max: 800,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "clear_height",
      name: "clear_height",
      role: "DRIVING",
      type: "LENGTH",
      value: 200,
      unit: "mm",
      min: 100,
      max: 600,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "ext_wall",
      name: "ext_wall",
      role: "DRIVING",
      type: "LENGTH",
      value: 30,
      unit: "mm",
      min: 10,
      max: 80,
      step: 5,
      provenance: "UserConstraint",
    },
    {
      id: "mid_wall",
      name: "mid_wall",
      role: "DRIVING",
      type: "LENGTH",
      value: 40,
      unit: "mm",
      min: 10,
      max: 100,
      step: 5,
      provenance: "UserConstraint",
    },
    {
      id: "haunch_leg",
      name: "haunch_leg",
      role: "DRIVING",
      type: "LENGTH",
      value: 35,
      unit: "mm",
      min: 10,
      max: 80,
      step: 5,
      provenance: "UserConstraint",
    },
    {
      id: "total_width",
      name: "total_width",
      role: "DERIVED",
      type: "LENGTH",
      value: 600,
      unit: "mm",
      expr: "ext_wall + bay1_span + mid_wall + bay2_span + ext_wall",
      provenance: "UserFormula",
    },
    {
      id: "total_height",
      name: "total_height",
      role: "DERIVED",
      type: "LENGTH",
      value: 260,
      unit: "mm",
      expr: "clear_height + (ext_wall * 2)",
      provenance: "UserFormula",
    },
  ],
  expressions: [
    {
      targetParameterId: "total_width",
      expression: "ext_wall + bay1_span + mid_wall + bay2_span + ext_wall",
      dependencies: ["ext_wall", "bay1_span", "mid_wall", "bay2_span"],
      description: "Total culvert width across two bays",
    },
    {
      targetParameterId: "total_height",
      expression: "clear_height + (ext_wall * 2)",
      dependencies: ["clear_height", "ext_wall"],
      description: "Total culvert height including top and bottom slabs",
    },
  ],
  geometry: {
    points: [
      { id: "p_tl", x: 0, y: 0 },
      { id: "p_tr", x: 600, y: 0 },
      { id: "p_br", x: 600, y: 260 },
      { id: "p_bl", x: 0, y: 260 },
      // Bay 1 void points
      { id: "b1_tl", x: 65, y: 30 },
      { id: "b1_tr", x: 245, y: 30 },
      { id: "b1_rt", x: 280, y: 65 },
      { id: "b1_rb", x: 280, y: 195 },
      { id: "b1_br", x: 245, y: 230 },
      { id: "b1_bl", x: 65, y: 230 },
      { id: "b1_lb", x: 30, y: 195 },
      { id: "b1_lt", x: 30, y: 65 },
      // Bay 2 void points
      { id: "b2_tl", x: 355, y: 30 },
      { id: "b2_tr", x: 535, y: 30 },
      { id: "b2_rt", x: 570, y: 65 },
      { id: "b2_rb", x: 570, y: 195 },
      { id: "b2_br", x: 535, y: 230 },
      { id: "b2_bl", x: 355, y: 230 },
      { id: "b2_lb", x: 320, y: 195 },
      { id: "b2_lt", x: 320, y: 65 },
    ],
    lines: [
      { id: "l_out_top", p1: "p_tl", p2: "p_tr" },
      { id: "l_out_right", p1: "p_tr", p2: "p_br" },
      { id: "l_out_bottom", p1: "p_br", p2: "p_bl" },
      { id: "l_out_left", p1: "p_bl", p2: "p_tl" },
      // Bay 1
      { id: "b1_top", p1: "b1_tl", p2: "b1_tr" },
      { id: "b1_htr", p1: "b1_tr", p2: "b1_rt" },
      { id: "b1_right", p1: "b1_rt", p2: "b1_rb" },
      { id: "b1_hbr", p1: "b1_rb", p2: "b1_br" },
      { id: "b1_bottom", p1: "b1_br", p2: "b1_bl" },
      { id: "b1_hbl", p1: "b1_bl", p2: "b1_lb" },
      { id: "b1_left", p1: "b1_lb", p2: "b1_lt" },
      { id: "b1_htl", p1: "b1_lt", p2: "b1_tl" },
      // Bay 2
      { id: "b2_top", p1: "b2_tl", p2: "b2_tr" },
      { id: "b2_htr", p1: "b2_tr", p2: "b2_rt" },
      { id: "b2_right", p1: "b2_rt", p2: "b2_rb" },
      { id: "b2_hbr", p1: "b2_rb", p2: "b2_br" },
      { id: "b2_bottom", p1: "b2_br", p2: "b2_bl" },
      { id: "b2_hbl", p1: "b2_bl", p2: "b2_lb" },
      { id: "b2_left", p1: "b2_lb", p2: "b2_lt" },
      { id: "b2_htl", p1: "b2_lt", p2: "b2_tl" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    {
      id: "c2_top_h",
      kind: "horizontal",
      refs: ["l_out_top"],
      strength: "hard",
      driving: false,
      provenance: "GeometricFact",
      state: "active",
    },
    {
      id: "c2_total_width",
      kind: "distance_x",
      refs: ["p_tl", "p_tr"],
      paramRef: "total_width",
      strength: "driving",
      driving: true,
      provenance: "UserConstraint",
      state: "active",
    },
  ],
  ports: [
    {
      id: "port_left",
      kind: "edge",
      localFrame: {
        origin: { x: "0", y: "total_height / 2" },
        angle: "180",
      },
      direction: "bidirectional",
    },
    {
      id: "port_right",
      kind: "edge",
      localFrame: {
        origin: { x: "total_width", y: "total_height / 2" },
        angle: "0",
      },
      direction: "bidirectional",
    },
    {
      id: "port_top",
      kind: "edge",
      localFrame: {
        origin: { x: "total_width / 2", y: "0" },
        angle: "90",
      },
      direction: "out",
    },
  ],
  semantics: [
    {
      id: "sem_two_span",
      type: "two_span_box_culvert",
      faces: ["face_solid"],
      edges: ["l_out_top", "l_out_right", "l_out_bottom", "l_out_left"],
      children: [],
      params: ["bay1_span", "bay2_span", "mid_wall"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_two_bay_haunch",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "bay1_span > (haunch_leg * 2)",
      message: "Bay 1 span must exceed double the haunch leg length",
    },
  ],
  provenance: [
    {
      timestamp: "2026-09-09T00:00:00Z",
      action: "template_created",
      author: "UPCE_Core_Team",
    },
  ],
};

export const MULTI_CELL_BOX_CULVERT_TEMPLATE: TemplateDefinition = {
  id: "multi_cell_box_culvert",
  name: "Multi-Cell Box Culvert Assembly",
  category: "assembly",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  standardsReference: "IRS Concrete Bridge Code §4.3",
  parameters: [
    {
      id: "cell_count",
      name: "cell_count",
      role: "DRIVING",
      type: "COUNT",
      value: 3,
      unit: "count",
      min: 1,
      max: 10,
      step: 1,
      provenance: "UserConstraint",
    },
    {
      id: "cell_span",
      name: "cell_span",
      role: "DRIVING",
      type: "LENGTH",
      value: 300,
      unit: "mm",
      min: 100,
      max: 1000,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "clear_height",
      name: "clear_height",
      role: "DRIVING",
      type: "LENGTH",
      value: 200,
      unit: "mm",
      min: 100,
      max: 800,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "wall_thickness",
      name: "wall_thickness",
      role: "DRIVING",
      type: "LENGTH",
      value: 30,
      unit: "mm",
      min: 10,
      max: 100,
      step: 5,
      provenance: "UserConstraint",
    },
    {
      id: "haunch_leg",
      name: "haunch_leg",
      role: "DRIVING",
      type: "LENGTH",
      value: 35,
      unit: "mm",
      min: 10,
      max: 80,
      step: 5,
      provenance: "UserConstraint",
    },
    {
      id: "cell_spacing",
      name: "cell_spacing",
      role: "DERIVED",
      type: "LENGTH",
      value: 330,
      unit: "mm",
      expr: "cell_span + wall_thickness",
      provenance: "UserFormula",
    },
  ],
  expressions: [
    {
      targetParameterId: "cell_spacing",
      expression: "cell_span + wall_thickness",
      dependencies: ["cell_span", "wall_thickness"],
      description: "Center-to-center bay unit step spacing",
    },
  ],
  geometry: {
    points: [],
    lines: [],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [],
  ports: [
    {
      id: "port_inlet",
      kind: "edge",
      localFrame: {
        origin: { x: "0", y: "clear_height / 2 + wall_thickness" },
        angle: "180",
      },
      direction: "in",
    },
    {
      id: "port_outlet",
      kind: "edge",
      localFrame: {
        origin: { x: "cell_count * cell_spacing + wall_thickness", y: "clear_height / 2 + wall_thickness" },
        angle: "0",
      },
      direction: "out",
    },
  ],
  repeats: [
    {
      id: "cell_repeat",
      type: "linear_array",
      sourceComponent: "single_cell_box_culvert",
      countParamRef: "cell_count",
      spacingExpr: "cell_spacing",
      spacingMode: "driven",
      direction: [1, 0],
      anchorPortId: "port_left",
      indexVariable: "i",
      parameterOverrides: {
        clear_span: "cell_span",
        clear_height: "clear_height",
        wall_thickness: "wall_thickness",
        haunch_leg: "haunch_leg",
      },
    },
  ],
  semantics: [
    {
      id: "sem_multi_cell",
      type: "multi_cell_assembly",
      faces: [],
      edges: [],
      children: [],
      params: ["cell_count", "cell_span"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_cell_count_min",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "cell_count >= 1",
      message: "Multi-cell culvert must have at least 1 cell",
    },
  ],
  provenance: [
    {
      timestamp: "2026-09-09T00:00:00Z",
      action: "template_created",
      author: "UPCE_Core_Team",
    },
  ],
};

export const RAILING_POST_TEMPLATE: TemplateDefinition = {
  id: "railing_post",
  name: "Parametric Railing Post Component",
  category: "component",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  parameters: [
    {
      id: "post_height",
      name: "post_height",
      role: "DRIVING",
      type: "LENGTH",
      value: 900,
      unit: "mm",
      min: 400,
      max: 1600,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "post_width",
      name: "post_width",
      role: "DRIVING",
      type: "LENGTH",
      value: 60,
      unit: "mm",
      min: 20,
      max: 200,
      step: 5,
      provenance: "UserConstraint",
    },
  ],
  expressions: [],
  geometry: {
    points: [
      { id: "p0", x: 0, y: 0 },
      { id: "p1", x: 60, y: 0 },
      { id: "p2", x: 60, y: 900 },
      { id: "p3", x: 0, y: 900 },
    ],
    lines: [
      { id: "l_top", p1: "p0", p2: "p1" },
      { id: "l_right", p1: "p1", p2: "p2" },
      { id: "l_bottom", p1: "p2", p2: "p3" },
      { id: "l_left", p1: "p3", p2: "p0" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    {
      id: "c_post_h",
      kind: "horizontal",
      refs: ["l_top"],
      strength: "hard",
      driving: false,
      provenance: "GeometricFact",
      state: "active",
    },
    {
      id: "c_post_v",
      kind: "vertical",
      refs: ["l_left"],
      strength: "hard",
      driving: false,
      provenance: "GeometricFact",
      state: "active",
    },
  ],
  ports: [
    {
      id: "base_port",
      kind: "point",
      localFrame: {
        origin: { x: "post_width / 2", y: "post_height" },
        angle: "270",
      },
      direction: "out",
    },
    {
      id: "top_port",
      kind: "point",
      localFrame: {
        origin: { x: "post_width / 2", y: "0" },
        angle: "90",
      },
      direction: "out",
    },
    {
      id: "side_left",
      kind: "point",
      localFrame: {
        origin: { x: "0", y: "post_height / 2" },
        angle: "180",
      },
      direction: "bidirectional",
    },
    {
      id: "side_right",
      kind: "point",
      localFrame: {
        origin: { x: "post_width", y: "post_height / 2" },
        angle: "0",
      },
      direction: "bidirectional",
    },
  ],
  semantics: [
    {
      id: "sem_post",
      type: "railing_post",
      faces: ["post_face"],
      edges: ["l_top", "l_right", "l_bottom", "l_left"],
      children: [],
      params: ["post_height", "post_width"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_post_aspect",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "post_height > (post_width * 2)",
      message: "Post height must be substantially larger than post width",
    },
  ],
  provenance: [
    {
      timestamp: "2026-09-09T00:00:00Z",
      action: "template_created",
      author: "UPCE_Core_Team",
    },
  ],
};

export const RAILING_RUN_TEMPLATE: TemplateDefinition = {
  id: "railing_run",
  name: "Parametric Bridge Railing Run Assembly",
  category: "assembly",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  parameters: [
    {
      id: "run_length",
      name: "run_length",
      role: "DRIVING",
      type: "LENGTH",
      value: 3000,
      unit: "mm",
      min: 500,
      max: 20000,
      step: 50,
      provenance: "UserConstraint",
    },
    {
      id: "post_count",
      name: "post_count",
      role: "DRIVING",
      type: "COUNT",
      value: 5,
      unit: "count",
      min: 2,
      max: 50,
      step: 1,
      provenance: "UserConstraint",
    },
    {
      id: "post_height",
      name: "post_height",
      role: "DRIVING",
      type: "LENGTH",
      value: 900,
      unit: "mm",
      min: 400,
      max: 1600,
      step: 10,
      provenance: "UserConstraint",
    },
    {
      id: "post_width",
      name: "post_width",
      role: "DRIVING",
      type: "LENGTH",
      value: 60,
      unit: "mm",
      min: 20,
      max: 200,
      step: 5,
      provenance: "UserConstraint",
    },
    {
      id: "post_spacing",
      name: "post_spacing",
      role: "DERIVED",
      type: "LENGTH",
      value: 750,
      unit: "mm",
      expr: "run_length / (post_count - 1)",
      provenance: "UserFormula",
    },
  ],
  expressions: [
    {
      targetParameterId: "post_spacing",
      expression: "run_length / (post_count - 1)",
      dependencies: ["run_length", "post_count"],
      description: "Centerline spacing between successive railing posts",
    },
  ],
  geometry: {
    points: [
      { id: "rail_top_start", x: 0, y: 0 },
      { id: "rail_top_end", x: 3060, y: 0 },
      { id: "rail_mid_start", x: 0, y: 450 },
      { id: "rail_mid_end", x: 3060, y: 450 },
    ],
    lines: [
      { id: "l_handrail_top", p1: "rail_top_start", p2: "rail_top_end", semanticRole: "top_handrail" },
      { id: "l_handrail_mid", p1: "rail_mid_start", p2: "rail_mid_end", semanticRole: "mid_handrail" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [],
  ports: [
    {
      id: "run_start",
      kind: "point",
      localFrame: {
        origin: { x: "0", y: "post_height" },
        angle: "180",
      },
      direction: "bidirectional",
    },
    {
      id: "run_end",
      kind: "point",
      localFrame: {
        origin: { x: "run_length + post_width", y: "post_height" },
        angle: "0",
      },
      direction: "bidirectional",
    },
  ],
  repeats: [
    {
      id: "post_repeat",
      type: "linear_array",
      sourceComponent: "railing_post",
      countParamRef: "post_count",
      spacingExpr: "post_spacing",
      spacingMode: "derived",
      direction: [1, 0],
      anchorPortId: "base_port",
      indexVariable: "i",
      parameterOverrides: {
        post_height: "post_height",
        post_width: "post_width",
      },
    },
  ],
  semantics: [
    {
      id: "sem_railing_run",
      type: "railing_assembly",
      faces: [],
      edges: ["l_handrail_top", "l_handrail_mid"],
      children: [],
      params: ["run_length", "post_count"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_post_count_min",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "post_count >= 2",
      message: "Railing run must contain at least 2 posts",
    },
  ],
  provenance: [
    {
      timestamp: "2026-09-09T00:00:00Z",
      action: "template_created",
      author: "UPCE_Core_Team",
    },
  ],
};

export const RCC_BRIDGE_TEMPLATE: TemplateDefinition = {
  id: "rcc_bridge",
  name: "Standard RCC Bridge Assembly",
  category: "bridge",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  standardsReference: "IRC:21-2000 / IRC:112",
  parameters: [
    { id: "span", name: "span", role: "DRIVING", type: "LENGTH", value: 600, unit: "mm", min: 300, max: 2000, step: 20, provenance: "UserConstraint" },
    { id: "deck_width", name: "deck_width", role: "DRIVING", type: "LENGTH", value: 700, unit: "mm", min: 400, max: 2400, step: 20, provenance: "UserConstraint" },
    { id: "deck_thickness", name: "deck_thickness", role: "DRIVING", type: "LENGTH", value: 60, unit: "mm", min: 20, max: 200, step: 5, provenance: "UserConstraint" },
    { id: "pier_width", name: "pier_width", role: "DRIVING", type: "LENGTH", value: 60, unit: "mm", min: 30, max: 200, step: 5, provenance: "UserConstraint" },
    { id: "pier_height", name: "pier_height", role: "DRIVING", type: "LENGTH", value: 180, unit: "mm", min: 80, max: 600, step: 10, provenance: "UserConstraint" },
    { id: "pier_spacing", name: "pier_spacing", role: "DRIVING", type: "LENGTH", value: 340, unit: "mm", min: 150, max: 1200, step: 10, provenance: "UserConstraint" },
    { id: "parapet_height", name: "parapet_height", role: "DRIVING", type: "LENGTH", value: 35, unit: "mm", min: 15, max: 100, step: 5, provenance: "UserConstraint" },
    { id: "wall_thickness", name: "wall_thickness", role: "DRIVING", type: "LENGTH", value: 30, unit: "mm", min: 10, max: 80, step: 5, provenance: "UserConstraint" },
  ],
  expressions: [],
  geometry: {
    points: [
      { id: "d_tl", x: 0, y: 0 },
      { id: "d_tr", x: 700, y: 0 },
      { id: "d_br", x: 700, y: 60 },
      { id: "d_bl", x: 0, y: 60 },
      // Pier 1
      { id: "p1_tl", x: 150, y: 60 },
      { id: "p1_tr", x: 210, y: 60 },
      { id: "p1_br", x: 210, y: 240 },
      { id: "p1_bl", x: 150, y: 240 },
      // Pier 2
      { id: "p2_tl", x: 490, y: 60 },
      { id: "p2_tr", x: 550, y: 60 },
      { id: "p2_br", x: 550, y: 240 },
      { id: "p2_bl", x: 490, y: 240 },
    ],
    lines: [
      { id: "l_deck_top", p1: "d_tl", p2: "d_tr" },
      { id: "l_deck_right", p1: "d_tr", p2: "d_br" },
      { id: "l_deck_bottom", p1: "d_br", p2: "d_bl" },
      { id: "l_deck_left", p1: "d_bl", p2: "d_tl" },
      // Pier 1
      { id: "l_p1_l", p1: "p1_tl", p2: "p1_bl" },
      { id: "l_p1_b", p1: "p1_bl", p2: "p1_br" },
      { id: "l_p1_r", p1: "p1_br", p2: "p1_tr" },
      // Pier 2
      { id: "l_p2_l", p1: "p2_tl", p2: "p2_bl" },
      { id: "l_p2_b", p1: "p2_bl", p2: "p2_br" },
      { id: "l_p2_r", p1: "p2_br", p2: "p2_tr" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    { id: "c_deck_h", kind: "horizontal", refs: ["l_deck_top"], strength: "hard", driving: false, provenance: "GeometricFact", state: "active" },
  ],
  ports: [
    {
      id: "deck_left",
      kind: "point",
      localFrame: { origin: { x: "0", y: "0" }, angle: "180" },
      direction: "bidirectional",
    },
    {
      id: "deck_right",
      kind: "point",
      localFrame: { origin: { x: "deck_width", y: "0" }, angle: "0" },
      direction: "bidirectional",
    },
    {
      id: "pier1_base",
      kind: "point",
      localFrame: { origin: { x: "180", y: "deck_thickness + pier_height" }, angle: "270" },
      direction: "out",
    },
    {
      id: "pier2_base",
      kind: "point",
      localFrame: { origin: { x: "520", y: "deck_thickness + pier_height" }, angle: "270" },
      direction: "out",
    },
  ],
  semantics: [
    {
      id: "sem_rcc_bridge",
      type: "bridge_superstructure",
      faces: ["deck_face", "pier1_face", "pier2_face"],
      edges: ["l_deck_top", "l_deck_right", "l_deck_bottom", "l_deck_left"],
      children: [],
      params: ["span", "deck_width"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_pier_spacing",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "deck_width > (pier_spacing + pier_width)",
      message: "Deck width must safely encompass pier spacing plus pier width",
    },
  ],
  provenance: [
    { timestamp: "2026-09-09T00:00:00Z", action: "template_created", author: "UPCE_Core_Team" },
  ],
};

export const PARAMETRIC_FRAME_CUTOUT_TEMPLATE: TemplateDefinition = {
  id: "parametric_frame_cutout",
  name: "Parametric Frame with Inner Cutout",
  category: "component",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  parameters: [
    { id: "width", name: "width", role: "DRIVING", type: "LENGTH", value: 400, unit: "mm", min: 100, max: 1000, step: 10, provenance: "UserConstraint" },
    { id: "height", name: "height", role: "DRIVING", type: "LENGTH", value: 240, unit: "mm", min: 80, max: 600, step: 10, provenance: "UserConstraint" },
    { id: "wall_thickness", name: "wall_thickness", role: "DRIVING", type: "LENGTH", value: 30, unit: "mm", min: 5, max: 80, step: 5, provenance: "UserConstraint" },
    { id: "inner_width", name: "inner_width", role: "DERIVED", type: "LENGTH", value: 340, unit: "mm", expr: "width - (wall_thickness * 2)", provenance: "UserFormula" },
    { id: "inner_height", name: "inner_height", role: "DERIVED", type: "LENGTH", value: 180, unit: "mm", expr: "height - (wall_thickness * 2)", provenance: "UserFormula" },
  ],
  expressions: [
    {
      targetParameterId: "inner_width",
      expression: "width - (wall_thickness * 2)",
      dependencies: ["width", "wall_thickness"],
    },
    {
      targetParameterId: "inner_height",
      expression: "height - (wall_thickness * 2)",
      dependencies: ["height", "wall_thickness"],
    },
  ],
  geometry: {
    points: [
      { id: "o_tl", x: 0, y: 0 },
      { id: "o_tr", x: 400, y: 0 },
      { id: "o_br", x: 400, y: 240 },
      { id: "o_bl", x: 0, y: 240 },
      { id: "i_tl", x: 30, y: 30 },
      { id: "i_tr", x: 370, y: 30 },
      { id: "i_br", x: 370, y: 210 },
      { id: "i_bl", x: 30, y: 210 },
    ],
    lines: [
      { id: "lo_top", p1: "o_tl", p2: "o_tr" },
      { id: "lo_right", p1: "o_tr", p2: "o_br" },
      { id: "lo_bottom", p1: "o_br", p2: "o_bl" },
      { id: "lo_left", p1: "o_bl", p2: "o_tl" },
      { id: "li_top", p1: "i_tl", p2: "i_tr" },
      { id: "li_right", p1: "i_tr", p2: "i_br" },
      { id: "li_bottom", p1: "i_br", p2: "i_bl" },
      { id: "li_left", p1: "i_bl", p2: "i_tl" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    { id: "c_frame_w", kind: "distance_x", refs: ["o_tl", "o_tr"], paramRef: "width", strength: "driving", driving: true, provenance: "UserConstraint", state: "active" },
  ],
  ports: [
    {
      id: "mount_left",
      kind: "point",
      localFrame: { origin: { x: "0", y: "height / 2" }, angle: "180" },
      direction: "bidirectional",
    },
    {
      id: "mount_right",
      kind: "point",
      localFrame: { origin: { x: "width", y: "height / 2" }, angle: "0" },
      direction: "bidirectional",
    },
  ],
  semantics: [
    {
      id: "sem_frame",
      type: "frame_assembly",
      faces: ["frame_solid"],
      edges: ["lo_top", "lo_right", "lo_bottom", "lo_left"],
      children: [],
      params: ["width", "height"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_frame_cutout",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "width > (wall_thickness * 2)",
      message: "Outer width must exceed double the wall thickness",
    },
  ],
  provenance: [
    { timestamp: "2026-09-09T00:00:00Z", action: "template_created", author: "UPCE_Core_Team" },
  ],
};

export const SQUARE_TUBE_PROFILE_TEMPLATE: TemplateDefinition = {
  id: "square_tube_profile",
  name: "Square Box Tube Profile",
  category: "component",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  parameters: [
    { id: "size", name: "size", role: "DRIVING", type: "LENGTH", value: 250, unit: "mm", min: 50, max: 600, step: 10, provenance: "UserConstraint" },
    { id: "thickness", name: "thickness", role: "DRIVING", type: "LENGTH", value: 20, unit: "mm", min: 2, max: 50, step: 2, provenance: "UserConstraint" },
    { id: "inner_size", name: "inner_size", role: "DERIVED", type: "LENGTH", value: 210, unit: "mm", expr: "size - (thickness * 2)", provenance: "UserFormula" },
  ],
  expressions: [
    {
      targetParameterId: "inner_size",
      expression: "size - (thickness * 2)",
      dependencies: ["size", "thickness"],
    },
  ],
  geometry: {
    points: [
      { id: "t_tl", x: 0, y: 0 },
      { id: "t_tr", x: 250, y: 0 },
      { id: "t_br", x: 250, y: 250 },
      { id: "t_bl", x: 0, y: 250 },
      { id: "ti_tl", x: 20, y: 20 },
      { id: "ti_tr", x: 230, y: 20 },
      { id: "ti_br", x: 230, y: 230 },
      { id: "ti_bl", x: 20, y: 230 },
    ],
    lines: [
      { id: "lt_top", p1: "t_tl", p2: "t_tr" },
      { id: "lt_right", p1: "t_tr", p2: "t_br" },
      { id: "lt_bottom", p1: "t_br", p2: "t_bl" },
      { id: "lt_left", p1: "t_bl", p2: "t_tl" },
      { id: "lti_top", p1: "ti_tl", p2: "ti_tr" },
      { id: "lti_right", p1: "ti_tr", p2: "ti_br" },
      { id: "lti_bottom", p1: "ti_br", p2: "ti_bl" },
      { id: "lti_left", p1: "ti_bl", p2: "ti_tl" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    { id: "c_tube_size", kind: "equal_length", refs: ["lt_top", "lt_left"], strength: "hard", driving: false, provenance: "GeometricFact", state: "active" },
  ],
  ports: [
    {
      id: "center_axis",
      kind: "point",
      localFrame: { origin: { x: "size / 2", y: "size / 2" }, angle: "0" },
      direction: "bidirectional",
    },
    {
      id: "edge_top",
      kind: "edge",
      localFrame: { origin: { x: "size / 2", y: "0" }, angle: "90" },
      direction: "out",
    },
  ],
  semantics: [
    {
      id: "sem_tube",
      type: "structural_tube",
      faces: ["tube_face"],
      edges: ["lt_top", "lt_right", "lt_bottom", "lt_left"],
      children: [],
      params: ["size", "thickness"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_tube_wall",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "size > (thickness * 2)",
      message: "Tube size must exceed double the wall thickness",
    },
  ],
  provenance: [
    { timestamp: "2026-09-09T00:00:00Z", action: "template_created", author: "UPCE_Core_Team" },
  ],
};

export const CHAMFERED_OCTAGONAL_POLYGON_TEMPLATE: TemplateDefinition = {
  id: "chamfered_octagonal_polygon",
  name: "8-Sided Chamfered Polygon Profile",
  category: "component",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  parameters: [
    { id: "top_edge_length", name: "top_edge_length", role: "DRIVING", type: "LENGTH", value: 177, unit: "mm", min: 50, max: 400, step: 1, provenance: "UserConstraint" },
    { id: "tr_chamfer_length", name: "tr_chamfer_length", role: "DRIVING", type: "LENGTH", value: 38, unit: "mm", min: 10, max: 100, step: 1, provenance: "UserConstraint" },
    { id: "right_edge_length", name: "right_edge_length", role: "DRIVING", type: "LENGTH", value: 92, unit: "mm", min: 30, max: 300, step: 1, provenance: "UserConstraint" },
    { id: "br_chamfer_length", name: "br_chamfer_length", role: "DRIVING", type: "LENGTH", value: 38, unit: "mm", min: 10, max: 100, step: 1, provenance: "UserConstraint" },
    { id: "bottom_edge_length", name: "bottom_edge_length", role: "DRIVING", type: "LENGTH", value: 176, unit: "mm", min: 50, max: 400, step: 1, provenance: "UserConstraint" },
    { id: "bl_chamfer_length", name: "bl_chamfer_length", role: "DRIVING", type: "LENGTH", value: 46, unit: "mm", min: 10, max: 100, step: 1, provenance: "UserConstraint" },
    { id: "left_edge_length", name: "left_edge_length", role: "DRIVING", type: "LENGTH", value: 79, unit: "mm", min: 30, max: 300, step: 1, provenance: "UserConstraint" },
    { id: "tl_chamfer_length", name: "tl_chamfer_length", role: "DRIVING", type: "LENGTH", value: 44, unit: "mm", min: 10, max: 100, step: 1, provenance: "UserConstraint" },
  ],
  expressions: [],
  geometry: {
    points: [
      { id: "v0", x: 150, y: 100 },
      { id: "v1", x: 327, y: 100 },
      { id: "v2", x: 353.87, y: 126.87 },
      { id: "v3", x: 353.87, y: 218.87 },
      { id: "v4", x: 327, y: 245.74 },
      { id: "v5", x: 151, y: 245.74 },
      { id: "v6", x: 118.47, y: 213.21 },
      { id: "v7", x: 118.47, y: 134.21 },
    ],
    lines: [
      { id: "e_top", p1: "v0", p2: "v1" },
      { id: "e_tr", p1: "v1", p2: "v2" },
      { id: "e_right", p1: "v2", p2: "v3" },
      { id: "e_br", p1: "v3", p2: "v4" },
      { id: "e_bottom", p1: "v4", p2: "v5" },
      { id: "e_bl", p1: "v5", p2: "v6" },
      { id: "e_left", p1: "v6", p2: "v7" },
      { id: "e_tl", p1: "v7", p2: "v0" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    { id: "c_oct_top_h", kind: "horizontal", refs: ["e_top"], strength: "hard", driving: false, provenance: "GeometricFact", state: "active" },
    { id: "c_oct_right_v", kind: "vertical", refs: ["e_right"], strength: "hard", driving: false, provenance: "GeometricFact", state: "active" },
  ],
  ports: [
    {
      id: "centroid_port",
      kind: "point",
      localFrame: { origin: { x: "235", y: "172" }, angle: "0" },
      direction: "bidirectional",
    },
  ],
  semantics: [
    {
      id: "sem_oct_poly",
      type: "chamfered_polygon",
      faces: ["oct_face"],
      edges: ["e_top", "e_tr", "e_right", "e_br", "e_bottom", "e_bl", "e_left", "e_tl"],
      children: [],
      params: ["top_edge_length", "tr_chamfer_length"],
      confirmedBy: "author",
    },
  ],
  validation: [],
  provenance: [
    { timestamp: "2026-09-09T00:00:00Z", action: "template_created", author: "UPCE_Core_Team" },
  ],
};

export const RDSO_BOX_BRIDGE_TEMPLATE: TemplateDefinition = {
  id: "rdso_box_bridge",
  name: "RDSO Standard Multi-Cell Box Bridge",
  category: "bridge",
  schemaVersion: "1.0",
  engineVersion: "1.0.0",
  standardsReference: "RDSO Standard Drawing B-10158",
  parameters: [
    { id: "cellCount", name: "cellCount", role: "DRIVING", type: "COUNT", value: 3, unit: "count", min: 1, max: 6, step: 1, provenance: "UserConstraint" },
    { id: "clearSpan", name: "clearSpan", role: "DRIVING", type: "LENGTH", value: 2000, unit: "mm", min: 1000, max: 6000, step: 100, provenance: "UserConstraint" },
    { id: "wallThickness", name: "wallThickness", role: "DRIVING", type: "LENGTH", value: 350, unit: "mm", min: 200, max: 600, step: 25, provenance: "UserConstraint" },
    { id: "barrelLength", name: "barrelLength", role: "DRIVING", type: "LENGTH", value: 6850, unit: "mm", min: 3000, max: 15000, step: 50, provenance: "UserConstraint" },
    { id: "curtainWallSpan", name: "curtainWallSpan", role: "DRIVING", type: "LENGTH", value: 9150, unit: "mm", min: 4000, max: 20000, step: 50, provenance: "UserConstraint" },
    { id: "dropWallThickness", name: "dropWallThickness", role: "DRIVING", type: "LENGTH", value: 250, unit: "mm", min: 150, max: 500, step: 25, provenance: "UserConstraint" },
    { id: "trackSpacing", name: "trackSpacing", role: "DRIVING", type: "LENGTH", value: 6260, unit: "mm", min: 4000, max: 10000, step: 20, provenance: "UserConstraint" },
  ],
  expressions: [],
  geometry: {
    points: [
      { id: "b_tl", x: 0, y: 0 },
      { id: "b_tr", x: 6850, y: 0 },
      { id: "b_br", x: 6850, y: 2700 },
      { id: "b_bl", x: 0, y: 2700 },
    ],
    lines: [
      { id: "l_barrel_top", p1: "b_tl", p2: "b_tr" },
      { id: "l_barrel_right", p1: "b_tr", p2: "b_br" },
      { id: "l_barrel_bottom", p1: "b_br", p2: "b_bl" },
      { id: "l_barrel_left", p1: "b_bl", p2: "b_tl" },
    ],
    arcs: [],
    circles: [],
    polylines: [],
  },
  constraints: [
    { id: "c_rdso_barrel_h", kind: "horizontal", refs: ["l_barrel_top"], strength: "hard", driving: false, provenance: "GeometricFact", state: "active" },
  ],
  ports: [
    {
      id: "track_1_center",
      kind: "axis",
      localFrame: { origin: { x: "2000", y: "0" }, angle: "90" },
      direction: "bidirectional",
    },
    {
      id: "track_2_center",
      kind: "axis",
      localFrame: { origin: { x: "2000 + trackSpacing", y: "0" }, angle: "90" },
      direction: "bidirectional",
    },
    {
      id: "wing_wall_left",
      kind: "edge",
      localFrame: { origin: { x: "0", y: "1350" }, angle: "180" },
      direction: "out",
    },
    {
      id: "wing_wall_right",
      kind: "edge",
      localFrame: { origin: { x: "barrelLength", y: "1350" }, angle: "0" },
      direction: "out",
    },
  ],
  semantics: [
    {
      id: "sem_rdso_bridge",
      type: "rdso_box_bridge",
      faces: ["barrel_face"],
      edges: ["l_barrel_top", "l_barrel_right", "l_barrel_bottom", "l_barrel_left"],
      children: [],
      params: ["cellCount", "clearSpan", "barrelLength"],
      confirmedBy: "author",
    },
  ],
  validation: [
    {
      ruleId: "val_rdso_cell_count",
      type: "BOUNDS",
      severity: "ERROR",
      expression: "cellCount >= 1 && cellCount <= 6",
      message: "RDSO standard box bridge accommodates 1 to 6 cells",
    },
  ],
  provenance: [
    { timestamp: "2026-09-09T00:00:00Z", action: "template_created", author: "UPCE_Core_Team" },
  ],
};

export const CANONICAL_TEMPLATES: TemplateDefinition[] = [
  SINGLE_CELL_BOX_CULVERT_TEMPLATE,
  TWO_CELL_BOX_CULVERT_TEMPLATE,
  MULTI_CELL_BOX_CULVERT_TEMPLATE,
  RAILING_POST_TEMPLATE,
  RAILING_RUN_TEMPLATE,
  RCC_BRIDGE_TEMPLATE,
  PARAMETRIC_FRAME_CUTOUT_TEMPLATE,
  SQUARE_TUBE_PROFILE_TEMPLATE,
  CHAMFERED_OCTAGONAL_POLYGON_TEMPLATE,
  RDSO_BOX_BRIDGE_TEMPLATE,
];
