"use client";

/**
 * The AUTHOR dock — the draftsman's parametric authoring workflow.
 *
 * The panel is ordered the way the work is actually done, not the way the
 * architecture is layered:
 *
 *     analyse  ->  review what was found  ->  see what is still free
 *              ->  answer the design questions  ->  name the values
 *              ->  group and repeat  ->  check  ->  publish
 *
 * Two rules from the brief are visible in every section below:
 *
 *   §3.3  a candidate says what was detected, from which measurements, how far
 *         off it is, and what accepting it will preserve. Nothing is applied
 *         until the author presses Accept.
 *
 *   §13   the author must be able to tell apart a measured fact, an accepted
 *         inference, a driving value, a derived value and a system default —
 *         so every parameter row carries its origin, and every derived value
 *         can be asked "why do you exist?".
 */

import React from "react";
import {
  Check,
  X,
  Sparkles,
  Scan,
  HelpCircle,
  Lock,
  ChevronRight,
  Boxes,
  Repeat,
  ClipboardCheck,
  Upload,
  Undo2,
  Info,
  TriangleAlert,
  CircleCheck,
  CircleX,
  Trash2,
  Eye,
  EyeOff,
  Link2,
  Link2Off,
  Ruler,
  GitCompare,
  Crosshair,
} from "lucide-react";
import { useDrawing } from "@/lib/state/drawingContext";
import { useUpce } from "../parametric/upceContext";
import { Group, Pill, Segmented } from "./ui/Disclosure";
import { ComponentRelationships } from "../bridge/ComponentRelationships";
import { ParametricModel } from "../bridge/ParametricModel";
import { Empty } from "./DraftPanel";
import type { ConstraintCandidate, DerivedCandidate, SketchParameter } from "@/lib/upce/types";
import type { IntentAction } from "@/lib/upce/completion";
import type { Measurable, LineRelationKind } from "@/lib/upce/link";

const ORIGIN_LABEL: Record<string, string> = {
  "geometric-fact": "Part of the shape",
  "inference-accepted": "Detected, then accepted",
  user: "You created this",
  "completion-assistant": "Chosen from a suggestion",
  template: "Came with the template",
  component: "Generated by a repeat",
};

const ROLE_TONE: Record<string, string> = {
  DRIVING: "bg-(--pen-soft) text-(--pen)",
  DERIVED: "bg-(--ink-sunken) text-(--dim-derived)",
  FIXED: "bg-(--ink-sunken) text-(--fg-muted)",
  MEASURED: "bg-(--ink-sunken) text-(--fg-muted)",
};


/**
 * Step 4b - relationships the drawing gives no evidence for.
 *
 * Everything above this point is the system proposing and the author choosing.
 * This is the author asserting: these two things are related because I say so.
 * It is the only place in the panel where intent comes from nowhere but the
 * engineer's head, which is exactly §20 of the brief - the normal workflow must
 * not need it, and an author who wants it must have it.
 *
 * Two halves, because a relationship needs both:
 *
 *   MEASURE  select geometry, name what it measures. Until a span has a name
 *            there is nothing an expression can refer to, and the assistant only
 *            offers to name one when naming it removes freedom - so a value you
 *            want purely in order to REFER to it was unreachable. "Report only"
 *            covers that: it records the number without holding the geometry, so
 *            it can never conflict with anything.
 *
 *   LINK     pick a named value and write what it follows. The constraint that
 *            reads it does not change, so the geometry goes on obeying the same
 *            rule; only the source of the number moves. That is why this works
 *            between shapes that share no constraint at all - the link lives in
 *            the scalar graph, and the geometric graph never learns of it (§9).
 */

/**
 * Relationships between two things the drawing says nothing about.
 *
 * Notebook pages 4-6 and 9, in one place. The assistant above can only propose
 * what it can SEE — two edges already parallel, a profile already nested inside
 * another. These are the opposite case: two lines or two shapes that share
 * nothing, tied together because the engineering says so and for no other
 * reason. That is why they are asserted here rather than offered there.
 *
 * Both halves work off the canvas selection, because pointing at the geometry is
 * how a draftsman says which things they mean.
 */
/** One of the two ways to assert a relationship between two pieces of geometry. */
function AssertRelationSection({ pane }: { pane: "edge" | "centre" }) {
  const upce = useUpce();
  const { state } = useDrawing();
  const {
    edgesFor, loopsFor, relationOptionsFor, relateTwoLines, relateTwoCentres,
    shapeRisk, shapeRiskFor, holdShapesOf, dismissShapeRisk,
  } = upce;

  const selection = React.useMemo(
    () => (state.selectedIds.length > 0 ? state.selectedIds : state.selectedId ? [state.selectedId] : []),
    [state.selectedIds, state.selectedId]
  );

  const edges = React.useMemo(() => (selection.length ? edgesFor(selection) : []), [selection, edgesFor]);
  const loops = React.useMemo(() => (selection.length ? loopsFor(selection) : []), [selection, loopsFor]);

  const [edgeA, setEdgeA] = React.useState("");
  const [edgeB, setEdgeB] = React.useState("");
  const [kind, setKind] = React.useState<LineRelationKind>("normal_offset");

  const options = React.useMemo(
    () => (edgeA && edgeB && edgeA !== edgeB ? relationOptionsFor(edgeA, edgeB) : []),
    [edgeA, edgeB, relationOptionsFor]
  );
  const riskNow = React.useMemo(
    () => (selection.length ? shapeRiskFor(selection) : null),
    [selection, shapeRiskFor]
  );
  const chosen = options.find((o) => o.kind === kind);

  return (
    <>

      {/* The rule was created and something it touches can still change shape. */}
      {shapeRisk && (
        <div className="rounded-[6px] border border-(--warn) bg-(--warn-soft) px-2.5 py-2 flex flex-col gap-1.5">
          <p className="text-[10.5px] leading-[1.5] text-(--fg-primary)">{shapeRisk.message}</p>
          <div className="flex items-center gap-1.5">
            <Button onClick={() => holdShapesOf(shapeRisk.shapeIds)} icon={Lock} tone="primary">
              Hold their shape
            </Button>
            <Button onClick={dismissShapeRisk} tone="quiet">
              Leave them free
            </Button>
          </div>
        </div>
      )}

      {/* Before the rule is made, so it can be prevented rather than repaired. */}
      {!shapeRisk && selection.length > 0 && riskNow && (
        <div className="rounded-[6px] border border-dashed border-(--rule) px-2.5 py-2 flex flex-col gap-1.5">
          <p className="text-[10.5px] leading-[1.5] text-(--fg-muted)">
            {riskNow} A rule that moves {selection.length === 1 ? "it" : "them"} may squash{" "}
            {selection.length === 1 ? "it" : "them"} instead — deforming a loose outline costs the
            solver less than carrying it across the sheet.
          </p>
          <Button onClick={() => holdShapesOf(selection)} icon={Lock}>
            Hold their shape first
          </Button>
        </div>
      )}

      {pane === "edge" && (
      <div className="rounded-[6px] border border-(--rule) overflow-hidden">
        <div className="px-2.5 h-[26px] flex items-center gap-1.5 bg-(--ink-raised) border-b border-(--rule)">
          <GitCompare className="w-[12px] h-[12px] text-(--fg-muted)" strokeWidth={2.1} />
          <span className="text-[11px] text-(--fg-secondary)">Hold one edge relative to another</span>
        </div>
        {edges.length < 2 ? (
          <p className="px-2.5 py-2 text-[10.5px] text-(--fg-muted)">
            Select geometry with at least two edges between it.
          </p>
        ) : (
          <div className="px-2.5 py-2 flex flex-col gap-1.5">
            <select
              value={edgeA}
              onChange={(e) => setEdgeA(e.target.value)}
              className="h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            >
              <option value="">Reference edge…</option>
              {edges.map((e) => (
                <option key={e.segmentId} value={e.segmentId}>{e.label}</option>
              ))}
            </select>
            <select
              value={edgeB}
              onChange={(e) => setEdgeB(e.target.value)}
              className="h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            >
              <option value="">Edge that follows it…</option>
              {edges.filter((e) => e.segmentId !== edgeA).map((e) => (
                <option key={e.segmentId} value={e.segmentId}>{e.label}</option>
              ))}
            </select>

            {options.length > 0 && (
              <div className="flex flex-col gap-1">
                {options.map((o) => (
                  <button
                    key={o.kind}
                    onClick={() => setKind(o.kind)}
                    className={`text-left px-2 py-1.5 rounded-[5px] border text-[10.5px] leading-[1.45] cursor-pointer ${
                      kind === o.kind
                        ? "border-(--pen) bg-(--ink-raised) text-(--fg-primary)"
                        : "border-(--rule) text-(--fg-muted) hover:text-(--fg-primary)"
                    }`}
                  >
                    <span className="block text-(--fg-primary)">{o.label}</span>
                    <span className="num opacity-70">measures {o.measured.toFixed(1)} mm now</span>
                  </button>
                ))}
              </div>
            )}
            {chosen && <p className="text-[10px] leading-[1.5] text-(--fg-muted)">{chosen.rationale}</p>}

            <Button
              onClick={() => {
                relateTwoLines(edgeA, edgeB, kind);
                setEdgeA("");
                setEdgeB("");
              }}
              disabled={!edgeA || !edgeB || edgeA === edgeB}
              icon={GitCompare}
              tone="primary"
            >
              Hold this relationship
            </Button>
          </div>
        )}
      </div>

      )}

      {pane === "centre" && (
      <div className="rounded-[6px] border border-(--rule) overflow-hidden">
        <div className="px-2.5 h-[26px] flex items-center gap-1.5 bg-(--ink-raised) border-b border-(--rule)">
          <Crosshair className="w-[12px] h-[12px] text-(--fg-muted)" strokeWidth={2.1} />
          <span className="text-[11px] text-(--fg-secondary)">Drive the gap between two centres</span>
        </div>
        {loops.length < 2 ? (
          <p className="px-2.5 py-2 text-[10.5px] text-(--fg-muted)">
            Select two closed shapes. Works on rectangles, circles and anything drawn from
            lines — the centre comes from the boundary, not from the shape&apos;s type.
          </p>
        ) : (
          <div className="px-2.5 py-2 flex flex-col gap-1.5">
            <p className="text-[10.5px] leading-[1.5] text-(--fg-muted)">
              Ties <span className="text-(--fg-primary)">{loops[0].label}</span> to{" "}
              <span className="text-(--fg-primary)">{loops[1].label}</span>. Lowering the value
              brings both in; raising it pushes both out.
            </p>
            <Button
              onClick={() => relateTwoCentres(loops[0].loop, loops[1].loop, loops[0].label, loops[1].label)}
              icon={Crosshair}
              tone="primary"
            >
              Name the centre-to-centre distance
            </Button>
          </div>
        )}
      </div>
      )}
    </>
  );
}

/** One of the two ways to turn a measurement into a named, driven value. */
function RelationshipSection({ pane }: { pane: "measure" | "formula" }) {
  const upce = useUpce();
  const { state } = useDrawing();
  const { sketch, measurablesFor, nameMeasurementAs, linkValue, unlinkValue } = upce;

  const selection = React.useMemo(
    () => (state.selectedIds.length > 0 ? state.selectedIds : state.selectedId ? [state.selectedId] : []),
    [state.selectedIds, state.selectedId]
  );
  const measurables = React.useMemo(
    () => (selection.length > 0 ? measurablesFor(selection) : []),
    [selection, measurablesFor]
  );

  const [chosen, setChosen] = React.useState<string>("");
  const [measureName, setMeasureName] = React.useState("");
  const [mode, setMode] = React.useState<"driving" | "reference">("driving");
  const [target, setTarget] = React.useState<string>("");
  const [expr, setExpr] = React.useState("");

  const active: Measurable | undefined =
    measurables.find((m) => m.id === chosen) ?? measurables[0];

  React.useEffect(() => {
    if (active && !measureName) setMeasureName(active.suggestedName);
  }, [active, measureName]);

  const parameters = Object.values(sketch.parameters);
  const linkable = parameters.filter((p) => p.role === "DRIVING" || p.role === "DERIVED");
  const current = target ? sketch.parameters[target] : undefined;

  // Evaluate what the author has typed against the real parameter values, so a
  // typo shows up here rather than as a refused edit after they press the button.
  const preview = React.useMemo(() => {
    if (!expr.trim() || !target) return null;
    const names: string[] = expr.match(/[A-Za-z_][A-Za-z0-9_]*/g) ?? [];
    const builtins: string[] = ["max", "min", "abs", "round", "ceil", "floor", "sqrt"];
    const unknown = names.filter((n) => !sketch.parameters[n] && !builtins.includes(n));
    if (unknown.length > 0) return { ok: false as const, text: `No value called ${unknown[0]}.` };
    if (names.includes(target)) return { ok: false as const, text: `${target} cannot be written in terms of itself.` };
    return { ok: true as const, text: `${target} stops being typed and follows this instead.` };
  }, [expr, target, sketch.parameters]);

  return (
    <>
      {pane === "measure" && (
      <div className="rounded-[6px] border border-(--rule) overflow-hidden">
        <div className="px-2.5 h-[26px] flex items-center gap-1.5 bg-(--ink-raised) border-b border-(--rule)">
          <Ruler className="w-[12px] h-[12px] text-(--fg-muted)" strokeWidth={2.1} />
          <span className="text-[11px] text-(--fg-secondary)">Measure and name</span>
        </div>
        {selection.length === 0 ? (
          <p className="px-2.5 py-2 text-[10.5px] text-(--fg-muted)">
            Select geometry on the canvas. Select two things to measure the gap between them.
          </p>
        ) : measurables.length === 0 ? (
          <p className="px-2.5 py-2 text-[10.5px] text-(--fg-muted)">
            Nothing measurable in that selection — it has no extent the kernel can lower.
          </p>
        ) : (
          <div className="px-2.5 py-2 flex flex-col gap-1.5">
            <select
              value={active?.id ?? ""}
              onChange={(e) => {
                setChosen(e.target.value);
                const next = measurables.find((m) => m.id === e.target.value);
                setMeasureName(next?.suggestedName ?? "");
              }}
              className="h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            >
              {measurables.map((m) => (
                <option key={m.id} value={m.id}>
                  {m.label} — {m.value.toFixed(1)} mm
                </option>
              ))}
            </select>
            <div className="flex items-center gap-1.5">
              <input
                value={measureName}
                onChange={(e) => setMeasureName(e.target.value)}
                placeholder="Name"
                className="flex-1 min-w-0 h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
              />
              <select
                value={mode}
                onChange={(e) => setMode(e.target.value as "driving" | "reference")}
                title="A driving value holds the geometry to it. A report-only value records the number and holds nothing."
                className="h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
              >
                <option value="driving">drives it</option>
                <option value="reference">reports only</option>
              </select>
            </div>
            <Button
              onClick={() => {
                if (!active) return;
                nameMeasurementAs(active, measureName || active.suggestedName, mode);
                setMeasureName("");
              }}
              disabled={!active}
              icon={Ruler}
            >
              Name this measurement
            </Button>
          </div>
        )}
      </div>

      )}

      {pane === "formula" && (
      <div className="rounded-[6px] border border-(--rule) overflow-hidden">
        <div className="px-2.5 h-[26px] flex items-center gap-1.5 bg-(--ink-raised) border-b border-(--rule)">
          <Link2 className="w-[12px] h-[12px] text-(--fg-muted)" strokeWidth={2.1} />
          <span className="text-[11px] text-(--fg-secondary)">Make one value follow others</span>
        </div>
        {linkable.length === 0 ? (
          <p className="px-2.5 py-2 text-[10.5px] text-(--fg-muted)">
            No named values yet. Measure something above, or answer a design question.
          </p>
        ) : (
          <div className="px-2.5 py-2 flex flex-col gap-1.5">
            <div className="flex items-center gap-1.5">
              <select
                value={target}
                onChange={(e) => {
                  setTarget(e.target.value);
                  setExpr(sketch.parameters[e.target.value]?.expr ?? "");
                }}
                className="w-[112px] h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
              >
                <option value="">Which value…</option>
                {linkable.map((p) => (
                  <option key={p.name} value={p.name}>
                    {p.name}
                  </option>
                ))}
              </select>
              <span className="text-(--fg-muted) text-[11px]">=</span>
              <input
                value={expr}
                onChange={(e) => setExpr(e.target.value)}
                placeholder="OtherWidth - 2 * WallThickness"
                className="num flex-1 min-w-0 h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
              />
            </div>

            {/* Operands, so nobody has to remember a name or its spelling. */}
            <div className="flex flex-wrap gap-1">
              {parameters
                .filter((p) => p.name !== target)
                .map((p) => (
                  <button
                    key={p.name}
                    onClick={() => setExpr((e) => (e ? `${e} ${p.name}` : p.name))}
                    title={`${p.role} · ${p.value.toFixed(2)} ${p.unit}`}
                    className="px-1.5 h-[20px] rounded-[4px] text-[10px] border border-(--rule) text-(--fg-muted) hover:text-(--fg-primary) hover:border-(--rule-strong) cursor-pointer"
                  >
                    {p.name}
                    <span className="num ml-1 opacity-60">{p.value.toFixed(0)}</span>
                  </button>
                ))}
            </div>

            {preview && (
              <p className={`text-[10px] ${preview.ok ? "text-(--fg-muted)" : "text-(--danger)"}`}>
                {preview.text}
              </p>
            )}

            <div className="flex items-center gap-1.5">
              <Button
                onClick={() => {
                  linkValue(target, expr);
                  setExpr("");
                  setTarget("");
                }}
                disabled={!target || !expr.trim() || preview?.ok === false}
                icon={Link2}
                tone="primary"
              >
                Link it
              </Button>
              {current?.role === "DERIVED" && (
                <Button onClick={() => unlinkValue(current.name)} icon={Link2Off} tone="quiet">
                  Take back manual control
                </Button>
              )}
            </div>
          </div>
        )}
      </div>
      )}
    </>
  );
}

/**
 * Every way of relating two things, in one place, choosing between them.
 *
 * These were four separate boxes stacked down the column, each with its own
 * heading and its own pair of dropdowns, all open at once. They are alternatives
 * — you are doing exactly one of them — so a control that says so takes a
 * quarter of the room and asks one question instead of four.
 */
/**
 * The remaining freedoms, a few at a time.
 *
 * An under-defined drawing can have a dozen of these, and printing all twelve
 * turns the most useful panel in the app into a wall. The first few are the ones
 * worth acting on — the list is ordered by how simple the movement is — and the
 * rest are one click away for anyone who wants them.
 */
function FreedomList({ motions }: { motions: { description: string }[] }) {
  const [all, setAll] = React.useState(false);
  const SHOWN = 4;
  const shown = all ? motions : motions.slice(0, SHOWN);
  const hidden = motions.length - shown.length;

  return (
    <div className="px-2.5 py-2 flex flex-col gap-1">
      <ul className="flex flex-col gap-1">
        {shown.map((m, i) => (
          <li key={i} className="text-[10.5px] leading-[1.5] text-(--fg-secondary)">
            · {m.description}
          </li>
        ))}
      </ul>
      {hidden > 0 && (
        <button
          onClick={() => setAll(true)}
          className="self-start text-[10px] text-(--pen) hover:underline cursor-pointer"
        >
          {hidden} more
        </button>
      )}
      {all && motions.length > SHOWN && (
        <button
          onClick={() => setAll(false)}
          className="self-start text-[10px] text-(--fg-muted) hover:text-(--fg-primary) cursor-pointer"
        >
          Show fewer
        </button>
      )}
    </div>
  );
}

function RelationshipsGroup() {
  const [mode, setMode] = React.useState<"measure" | "formula" | "edge" | "centre">("measure");
  const { sketch } = useUpce();
  const derived = Object.values(sketch.parameters).filter((p) => p.role === "DERIVED").length;

  const blurb: Record<typeof mode, string> = {
    measure: "Measure something and give it a name, so it can be typed and published.",
    formula: "Make one named value follow others, with a formula you write.",
    edge: "Hold one edge against another. Move the first and the second comes with it.",
    centre: "Drive two closed shapes together or apart by the distance between their centres.",
  };

  return (
    <Group id="author.relationships" title="Relationships" count={derived > 0 ? derived : undefined}>
      <Segmented
        value={mode}
        onChange={setMode}
        options={[
          { value: "measure", label: "Measure", title: "Measure something and name it" },
          { value: "formula", label: "Formula", title: "Make one value follow others" },
          { value: "edge", label: "Edge", title: "Hold one edge relative to another" },
          { value: "centre", label: "Centre", title: "Drive the gap between two centres" },
        ]}
      />
      <p className="text-[10.5px] leading-[1.5] text-(--fg-muted)">{blurb[mode]}</p>

      {(mode === "measure" || mode === "formula") && <RelationshipSection pane={mode} />}
      {(mode === "edge" || mode === "centre") && <AssertRelationSection pane={mode} />}
    </Group>
  );
}

/** One measured figure, for a read-only schedule. */
function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="px-2.5 py-1 border-t border-(--rule) first:border-t-0 flex items-center justify-between gap-2">
      <span className="text-(--fg-muted)">{label}</span>
      <span className="num text-(--fg-secondary)">{value}</span>
    </div>
  );
}

function Button({
  onClick,
  children,
  icon: Icon,
  tone = "default",
  disabled,
  title,
}: {
  onClick: () => void;
  children: React.ReactNode;
  icon?: typeof Scan;
  tone?: "default" | "primary" | "quiet";
  disabled?: boolean;
  title?: string;
}) {
  const cls =
    tone === "primary"
      ? "bg-(--pen) text-(--ink-app) hover:opacity-90"
      : tone === "quiet"
        ? "text-(--fg-muted) hover:text-(--fg-primary) hover:bg-(--ink-raised)"
        : "border border-(--rule) text-(--fg-secondary) hover:text-(--fg-primary) hover:border-(--rule-strong)";
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      title={title}
      className={`h-[26px] px-2.5 rounded-[5px] text-[11.5px] font-medium inline-flex items-center gap-1.5 transition-colors duration-100 cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed ${cls}`}
    >
      {Icon && <Icon className="w-[12px] h-[12px]" strokeWidth={2.1} />}
      {children}
    </button>
  );
}

// ---------------------------------------------------------------------------

function NoticeBar() {
  const { notice, dismissNotice } = useUpce();
  if (!notice) return null;
  const tone =
    notice.kind === "error"
      ? "border-(--crit) bg-(--crit-soft) text-(--crit)"
      : notice.kind === "warn"
        ? "border-(--warn) bg-(--warn-soft) text-(--warn)"
        : notice.kind === "ok"
          ? "border-(--ok) bg-(--ok-soft) text-(--ok)"
          : "border-(--rule) bg-(--ink-raised) text-(--fg-secondary)";
  const Icon =
    notice.kind === "error" ? CircleX : notice.kind === "warn" ? TriangleAlert : notice.kind === "ok" ? CircleCheck : Info;
  return (
    <div className={`rounded-[6px] border px-2.5 py-2 flex items-start gap-2 ${tone}`}>
      <Icon className="w-[13px] h-[13px] mt-[1px] shrink-0" strokeWidth={2.1} />
      <p className="text-[11px] leading-[1.5] flex-1">{notice.text}</p>
      <button onClick={dismissNotice} className="shrink-0 cursor-pointer opacity-60 hover:opacity-100">
        <X className="w-[11px] h-[11px]" strokeWidth={2.4} />
      </button>
    </div>
  );
}

function CandidateCard({ candidate }: { candidate: ConstraintCandidate }) {
  const { acceptCandidate, rejectCandidate } = useUpce();
  const [open, setOpen] = React.useState(false);

  return (
    <article
      className={`rounded-[7px] border overflow-hidden ${
        candidate.admissible ? "border-(--rule) bg-(--ink-raised)" : "border-(--crit) bg-(--crit-soft)"
      }`}
    >
      <div className="px-2.5 pt-2 pb-2 flex flex-col gap-1.5">
        <p className="text-[12px] font-medium text-(--fg-primary) leading-snug">{candidate.headline}</p>

        <p className="text-[11px] leading-[1.5] text-(--fg-secondary)">{candidate.evidence[0]}</p>

        <div className="flex items-center gap-2 text-[10px] text-(--fg-muted)">
          <span>off by {candidate.deviation}</span>
          <span className="w-px h-[9px] bg-(--rule)" aria-hidden="true" />
          {candidate.admissible ? (
            <span>removes {candidate.dofRemoved} degree{candidate.dofRemoved === 1 ? "" : "s"} of freedom</span>
          ) : (
            <span className="text-(--crit)">{candidate.admissibilityNote}</span>
          )}
          {candidate.impliedCount ? (
            <>
              <span className="w-px h-[9px] bg-(--rule)" aria-hidden="true" />
              <span>settles {candidate.impliedCount} more like it</span>
            </>
          ) : null}
        </div>

        <button
          onClick={() => setOpen((v) => !v)}
          className="text-[10.5px] text-(--fg-muted) hover:text-(--fg-secondary) inline-flex items-center gap-1 self-start cursor-pointer"
        >
          <ChevronRight
            className={`w-[10px] h-[10px] transition-transform ${open ? "rotate-90" : ""}`}
            strokeWidth={2.2}
          />
          {open ? "Less" : "Why, and what it preserves"}
        </button>

        {open && (
          <div className="flex flex-col gap-1 pl-3 border-l border-(--rule) text-[10.5px] leading-[1.55] text-(--fg-muted)">
            {candidate.evidence.map((e, i) => (
              <p key={i}>{e}</p>
            ))}
            <p className="text-(--fg-secondary)">If you accept: {candidate.preserves}</p>
            <p>Affects {candidate.affectedShapeIds.join(", ")}.</p>
          </div>
        )}
      </div>

      {candidate.admissible && (
        <div className="flex border-t border-(--rule)">
          <button
            onClick={() => acceptCandidate(candidate.id)}
            className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--ok) hover:bg-(--ok-soft) cursor-pointer"
          >
            <Check className="w-[12px] h-[12px]" strokeWidth={2.4} />
            Accept
          </button>
          <div className="w-px bg-(--rule)" aria-hidden="true" />
          <button
            onClick={() => rejectCandidate(candidate.id)}
            className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--fg-muted) hover:bg-(--crit-soft) hover:text-(--crit) cursor-pointer"
          >
            <X className="w-[12px] h-[12px]" strokeWidth={2.4} />
            Not intended
          </button>
        </div>
      )}
    </article>
  );
}

function IntentOption({ option }: { option: IntentAction }) {
  const { applyIntent } = useUpce();
  const [open, setOpen] = React.useState(false);
  return (
    <div className="rounded-[6px] border border-(--rule) bg-(--ink-raised) overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full px-2.5 py-2 flex items-start gap-2 text-left cursor-pointer hover:bg-(--ink-sunken)"
      >
        <ChevronRight
          className={`w-[11px] h-[11px] mt-[2px] shrink-0 text-(--fg-muted) transition-transform ${open ? "rotate-90" : ""}`}
          strokeWidth={2.2}
        />
        <span className="flex-1 min-w-0">
          <span className="block text-[11.5px] text-(--fg-primary) leading-snug">{option.title}</span>
          <span className="block text-[10px] text-(--fg-muted) mt-0.5">
            {option.isDeliberateFreedom
              ? "leaves it free on purpose"
              : option.convertToDerived
                ? `${option.convertToDerived.name} stops being typed and starts being worked out`
                : `removes ${option.dofRemoved} degree${option.dofRemoved === 1 ? "" : "s"} of freedom`}
            {option.createsParameters.length > 0 &&
              ` · creates ${option.createsParameters.map((p) => p.name).join(", ")}`}
            {option.suppressConstraints && option.suppressConstraints.length > 0 &&
              ` · switches off ${option.suppressConstraints.length} rule${option.suppressConstraints.length === 1 ? "" : "s"} it makes redundant`}
          </span>
        </span>
      </button>
      {open && (
        <div className="px-2.5 pb-2 flex flex-col gap-1.5">
          <p className="text-[10.5px] leading-[1.55] text-(--fg-secondary)">{option.rationale}</p>
          {option.evidence.map((e, i) => (
            <p key={i} className="text-[10.5px] text-(--fg-muted)">
              {e}
            </p>
          ))}
          <Button
            onClick={() => {
              applyIntent(option);
              setOpen(false);
            }}
            tone="primary"
          >
            {option.isDeliberateFreedom ? "That is intended" : "This is what I meant"}
          </Button>
        </div>
      )}
    </div>
  );
}

function DerivedCard({ candidate }: { candidate: DerivedCandidate }) {
  const { acceptDerivedCandidate, rejectDerivedCandidate } = useUpce();
  return (
    <article className="rounded-[7px] border border-(--rule) bg-(--ink-raised) overflow-hidden">
      <div className="px-2.5 pt-2 pb-2 flex flex-col gap-1.5">
        <div className="flex items-baseline justify-between gap-2">
          <span className="text-[12px] font-medium text-(--fg-primary)">{candidate.name}</span>
          <span className="num text-[12px] text-(--fg-primary)">
            {candidate.value.toFixed(1)}
            <span className="text-(--fg-muted) ml-1 text-[10px]">mm</span>
          </span>
        </div>
        <p className="text-[11px] leading-[1.5] text-(--fg-secondary)">{candidate.headline}</p>
        <code className="num text-[10.5px] text-(--fg-muted) bg-(--ink-sunken) rounded px-1.5 py-1 overflow-x-auto whitespace-nowrap">
          {candidate.name} = {candidate.expr}
        </code>
        <div className="flex flex-col gap-0.5 text-[10px] text-(--fg-muted)">
          {candidate.evidence.map((e, i) => (
            <span key={i}>{e}</span>
          ))}
        </div>
      </div>
      <div className="flex border-t border-(--rule)">
        <button
          onClick={() => acceptDerivedCandidate(candidate.id)}
          className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--ok) hover:bg-(--ok-soft) cursor-pointer"
        >
          <Check className="w-[12px] h-[12px]" strokeWidth={2.4} />
          Keep it
        </button>
        <div className="w-px bg-(--rule)" aria-hidden="true" />
        <button
          onClick={() => rejectDerivedCandidate(candidate.id)}
          className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--fg-muted) hover:bg-(--crit-soft) hover:text-(--crit) cursor-pointer"
        >
          <X className="w-[12px] h-[12px]" strokeWidth={2.4} />
          Discard
        </button>
      </div>
    </article>
  );
}

function ParameterRow({ parameter }: { parameter: SketchParameter }) {
  const { setParameterValue, updateParameter, renameParameter, dependentsFor, sketch, createDerivedParameter } = useUpce();
  const [open, setOpen] = React.useState(false);
  const [draft, setDraft] = React.useState(String(parameter.value));
  const [nameDraft, setNameDraft] = React.useState(parameter.name);
  const [editingName, setEditingName] = React.useState(false);

  React.useEffect(() => setDraft(String(parameter.value)), [parameter.value]);

  const dependents = dependentsFor(parameter.name);
  const drives = parameter.boundConstraints
    .map((id) => sketch.constraints.find((c) => c.id === id)?.label)
    .filter(Boolean) as string[];

  return (
    <div className="border-t border-(--rule) first:border-t-0">
      <div className="flex items-center gap-2 px-2.5 h-[32px]">
        <span
          className={`text-[9px] px-1 rounded-sm font-semibold tracking-wide ${ROLE_TONE[parameter.role]}`}
        >
          {parameter.role.slice(0, 3)}
        </span>
        {editingName ? (
          <input
            autoFocus
            value={nameDraft}
            onChange={(e) => setNameDraft(e.target.value)}
            onBlur={() => {
              setEditingName(false);
              renameParameter(parameter.name, nameDraft);
            }}
            onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()}
            className="flex-1 min-w-0 h-[20px] px-1 text-[11.5px] bg-(--ink-sunken) border border-(--pen) rounded-[3px] outline-none text-(--fg-primary)"
          />
        ) : (
          <button
            onDoubleClick={() => setEditingName(true)}
            onClick={() => setOpen((v) => !v)}
            title="Double-click to rename"
            className="flex-1 min-w-0 text-left text-[11.5px] text-(--fg-secondary) truncate cursor-pointer hover:text-(--fg-primary)"
          >
            {parameter.name}
          </button>
        )}
        {parameter.role === "DRIVING" ? (
          <input
            value={draft}
            inputMode="decimal"
            onChange={(e) => setDraft(e.target.value)}
            onBlur={() => {
              const v = Number(draft);
              if (Number.isFinite(v) && v !== parameter.value) setParameterValue(parameter.name, v);
              else setDraft(String(parameter.value));
            }}
            onKeyDown={(e) => {
              if (e.key === "Enter") (e.target as HTMLInputElement).blur();
              if (e.key === "Escape") {
                setDraft(String(parameter.value));
                e.currentTarget.blur();
              }
            }}
            className="num w-[64px] h-[22px] px-1.5 text-right text-[11.5px] bg-(--ink-raised) border border-(--rule) rounded-[3px] outline-none focus:border-(--pen) text-(--fg-primary)"
          />
        ) : (
          <span className="num text-[11.5px] text-(--fg-muted) inline-flex items-center gap-1">
            <Lock className="w-[9px] h-[9px]" strokeWidth={2.2} />
            {parameter.value.toFixed(1)}
          </span>
        )}
        <span className="text-[9.5px] text-(--fg-muted) w-[24px]">{parameter.unit}</span>
      </div>

      {open && (
        <div className="px-2.5 pb-2.5 pt-0.5 flex flex-col gap-1.5 text-[10.5px] leading-[1.55]">
          <p className="text-(--fg-secondary)">
            <span className="text-(--fg-muted)">Origin · </span>
            {ORIGIN_LABEL[parameter.provenance.origin] ?? parameter.provenance.origin}
          </p>
          <p className="text-(--fg-muted)">{parameter.provenance.detail}</p>
          
          <div className="flex items-center gap-1.5 pt-1">
            <label className="text-(--fg-muted) shrink-0">Formula</label>
            <input
              key={parameter.expr ?? ""}
              defaultValue={parameter.expr ?? ""}
              placeholder="e.g. CellCount * CellPitch + 30"
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
              }}
              onBlur={(e) => {
                const expr = e.target.value.trim();
                if (expr && expr !== parameter.expr) {
                  createDerivedParameter(parameter.name, expr);
                } else if (!expr && parameter.expr) {
                  updateParameter(parameter.name, { role: "DRIVING", expr: undefined, dependencies: [] });
                }
              }}
              className="num flex-1 h-[22px] px-1.5 text-[10.5px] rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            />
          </div>

          {drives.length > 0 && (
            <div>
              <p className="text-(--fg-secondary)">Changing it moves:</p>
              <ul className="list-none pl-2">
                {drives.map((d, i) => (
                  <li key={i} className="text-(--fg-muted)">
                    · {d}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {dependents.length > 0 && (
            <p className="text-(--fg-muted)">Other values that follow it: {dependents.join(", ")}</p>
          )}
          <div className="flex items-center gap-2 pt-1">
            <label className="text-(--fg-muted)">Range</label>
            <input
              defaultValue={parameter.min ?? ""}
              placeholder="min"
              onBlur={(e) =>
                updateParameter(parameter.name, {
                  min: e.target.value === "" ? undefined : Number(e.target.value),
                })
              }
              className="num w-[52px] h-[20px] px-1 text-right text-[10.5px] rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen)"
            />
            <input
              defaultValue={parameter.max ?? ""}
              placeholder="max"
              onBlur={(e) =>
                updateParameter(parameter.name, {
                  max: e.target.value === "" ? undefined : Number(e.target.value),
                })
              }
              className="num w-[52px] h-[20px] px-1 text-right text-[10.5px] rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen)"
            />
            <label className="ml-auto inline-flex items-center gap-1 cursor-pointer text-(--fg-muted)">
              <input
                type="checkbox"
                checked={parameter.published}
                onChange={(e) => updateParameter(parameter.name, { published: e.target.checked })}
              />
              show to users
            </label>
          </div>
        </div>
      )}
    </div>
  );
}

function ConstraintRow({ id }: { id: string }) {
  const { sketch, deleteConstraint, toggleConstraint } = useUpce();
  const c = sketch.constraints.find((x) => x.id === id);
  const [open, setOpen] = React.useState(false);
  if (!c) return null;
  const isFact = c.strength === "fact";
  const suppressed = c.state === "suppressed";

  return (
    <div className="border-t border-(--rule) first:border-t-0">
      <div className="flex items-center gap-1.5 px-2.5 min-h-[28px] py-1">
        <button
          onClick={() => setOpen((v) => !v)}
          className={`flex-1 min-w-0 text-left text-[11px] leading-snug cursor-pointer ${
            suppressed ? "text-(--fg-muted) line-through" : "text-(--fg-secondary) hover:text-(--fg-primary)"
          }`}
        >
          {c.label}
          {c.paramRef && <span className="text-(--pen)"> = {c.paramRef}</span>}
        </button>
        <button
          onClick={() => toggleConstraint(c.id)}
          title={suppressed ? "Switch back on" : "Switch off temporarily"}
          className="shrink-0 w-[20px] h-[20px] grid place-items-center rounded text-(--fg-muted) hover:text-(--fg-primary) cursor-pointer disabled:opacity-30"
          disabled={isFact}
        >
          {suppressed ? <EyeOff className="w-[11px] h-[11px]" /> : <Eye className="w-[11px] h-[11px]" />}
        </button>
        <button
          onClick={() => deleteConstraint(c.id)}
          title={isFact ? "Part of the shape — cannot be removed here" : "Remove"}
          disabled={isFact}
          className="shrink-0 w-[20px] h-[20px] grid place-items-center rounded text-(--fg-muted) hover:text-(--crit) cursor-pointer disabled:opacity-30"
        >
          <Trash2 className="w-[11px] h-[11px]" />
        </button>
      </div>
      {open && (
        <p className="px-2.5 pb-2 text-[10.5px] leading-[1.55] text-(--fg-muted)">
          <span className="text-(--fg-secondary)">
            {ORIGIN_LABEL[c.provenance.origin] ?? c.provenance.origin} ·{" "}
          </span>
          {c.provenance.detail}
          {c.provenance.evidence?.length ? ` (${c.provenance.evidence.join("; ")})` : ""}
        </p>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------

export function AuthorPanel() {
  const { state, dispatch, selectedShapes, selectMultiple } = useDrawing();
  const upce = useUpce();
  const {
    started,
    sketch,
    dof,
    candidates,
    derived,
    completion,
    readiness,
    manifest,
    busy,
    analyse,
    acceptCandidate,
    refreshDerived,
    makeComponent,
    makeRepeat,
    setUnitRigid,
    measureUnitFor,
    setMergeOverlaps,
    repeatMeasurements,
    overlaps,
    fusion,
    setIntentionalFreedom,
    setTemplateName,
    checkReadiness,
    publishTemplate,
    undoIntent,
    canUndoIntent,
  } = upce;

  const { inversion, applyInversionOption, dismissInversion } = upce;
  const parameters = Object.values(sketch.parameters);
  const selection = state.selectedIds.length > 0 ? state.selectedIds : state.selectedId ? [state.selectedId] : [];

  const [componentName, setComponentName] = React.useState("Unit");
  const [repeatCount, setRepeatCount] = React.useState(3);
  const [repeatPitch, setRepeatPitch] = React.useState(0);
  const [spacingMode, setSpacingMode] = React.useState<"driven" | "derived" | "gap">("gap");
  const [repeatGap, setRepeatGap] = React.useState<number | null>(null);

  return (
    // Not `PanelBody`: the groups are full-bleed and separated by their own
    // rules, so a padded, gapped container would draw a second set of edges
    // inside the first and leave the panel looking like a list of boxes in a box.
    <div className="flex-1 min-h-0 overflow-y-auto flex flex-col">
      <div className="px-3 pt-3 flex flex-col gap-2.5 empty:hidden">
        <NoticeBar />
      </div>

      {/* The parametric model of the drawing's components, open: values,
          formulas, dependencies, constraints, dimensions and entities. */}
      {state.cad.components.length > 0 && (
        <Group id="author.model" title="Parametric model" defaultOpen>
          <ParametricModel />
        </Group>
      )}

      {/* Selected Entity Inspector Banner in Author Mode */}
      {selectedShapes.length > 0 && selectedShapes.every((sh) => !sh.componentInstanceId) && (
        <div className="mx-3 mt-2.5 rounded-[6px] border border-(--rule) bg-(--ink-raised) p-2.5 flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-semibold text-(--fg-primary) flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-(--pen)" />
              Selected: {selectedShapes.length === 1 ? selectedShapes[0].type : `${selectedShapes.length} shapes`}
            </span>
            {selectedShapes.length === 1 && (
              <span className="text-[10px] text-(--pen) font-mono bg-(--ink-sunken) px-1.5 py-0.5 rounded border border-(--rule) max-w-[130px] truncate" title={selectedShapes[0].id}>
                {selectedShapes[0].id}
              </span>
            )}
          </div>

          {selectedShapes.length === 1 ? (
            <div className="flex items-center gap-2">
              <label className="text-[11px] font-medium text-(--fg-muted) shrink-0">Name:</label>
              <input
                value={selectedShapes[0].name ?? ""}
                placeholder="Give this shape a name (e.g. Outer_Frame, Cell_Roof)"
                onChange={(e) =>
                  dispatch({
                    type: "UPDATE_SHAPE",
                    id: selectedShapes[0].id,
                    updates: { name: e.target.value },
                  })
                }
                className="flex-1 min-w-0 h-[24px] px-2 text-[11.5px] rounded-[4px] bg-(--ink-sunken) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary) font-mono"
              />
            </div>
          ) : (
            <div className="flex flex-wrap gap-1">
              {selectedShapes.map((s) => (
                <span key={s.id} className="text-[10px] bg-(--ink-sunken) border border-(--rule) px-1.5 py-0.5 rounded text-(--fg-secondary) font-mono">
                  {s.name || s.type}
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      {/* The status strip. It never collapses and never scrolls away, because it
          is the one thing a draftsman checks constantly — and because a panel
          whose groups can all be shut must never be able to hide that something
          is wrong. */}
      <div className="px-3 py-2.5 border-b border-(--rule) flex flex-col gap-2 shrink-0">
        <div className="flex items-center gap-1.5 flex-wrap">
          {!started ? (
            <Pill>not analysed</Pill>
          ) : dof ? (
            <>
              <Pill
                tone={dof.status === "well" ? "good" : dof.status === "over" ? "bad" : "neutral"}
                title={
                  dof.status === "well"
                    ? "Nothing can move on its own"
                    : dof.status === "over"
                      ? "Some requirements disagree"
                      : "Movements remain that nothing decides"
                }
              >
                {dof.status === "well"
                  ? "fully defined"
                  : dof.status === "over"
                    ? "conflict"
                    : `${dof.dof} free`}
              </Pill>
              <Pill title="Rules in force">{sketch.constraints.length} rules</Pill>
              <Pill title="Named values">{parameters.length} values</Pill>
            </>
          ) : null}
          <span className="flex-1" />
          {canUndoIntent && (
            <button
              onClick={undoIntent}
              title="Step back one design decision"
              className="text-[10px] text-(--fg-muted) hover:text-(--fg-primary) cursor-pointer whitespace-nowrap"
            >
              Step back
            </button>
          )}
        </div>

        <Button onClick={analyse} icon={Scan} tone={started ? "default" : "primary"}>
          {started ? "Re-read the drawing" : "Analyse geometry"}
        </Button>
      </div>

      {started && dof && (
        <Group
          id="author.freedom"
          title="What is still free"
          count={`${dof.dof} DOF`}
          tone={dof.status === "over" ? "bad" : dof.status === "under" ? "attention" : "good"}
          defaultOpen
        >
          <div className="rounded-[6px] border border-(--rule) overflow-hidden">
            <div
              className={`px-2.5 py-2 text-[11.5px] font-medium ${
                dof.status === "well"
                  ? "bg-(--ok-soft) text-(--ok)"
                  : dof.status === "over"
                    ? "bg-(--crit-soft) text-(--crit)"
                    : "bg-(--ink-sunken) text-(--fg-secondary)"
              }`}
            >
              {dof.status === "well"
                ? "Fully defined — nothing can move on its own"
                : dof.status === "over"
                  ? "Requirements conflict"
                  : `Under-defined — ${dof.dof} independent movement${dof.dof === 1 ? "" : "s"} remain`}
            </div>
            {dof.motions.length > 0 && <FreedomList motions={dof.motions} />}
            {dof.diagnoses.filter((d) => d.status !== "active").map((d) => (
              <div
                key={d.constraintId}
                className={`px-2.5 py-1.5 border-t border-(--rule) text-[10.5px] leading-[1.5] ${
                  d.status === "conflicting" ? "text-(--crit)" : "text-(--fg-muted)"
                }`}
              >
                <span className="font-medium">{d.label}</span> — {d.note}
              </div>
            ))}
          </div>
          {dof.dof > 0 && (
            <label className="flex items-center gap-1.5 text-[10.5px] text-(--fg-muted) cursor-pointer">
              <input
                type="checkbox"
                checked={sketch.meta.freedomIsIntentional}
                onChange={(e) => setIntentionalFreedom(e.target.checked)}
              />
              This freedom is intended — do not treat it as unfinished
            </label>
          )}
        </Group>
      )}

      {started && candidates.length > 0 && (
        <Group
          id="author.found"
          title="Found in the drawing"
          count={candidates.length}
          tone={candidates.length > 0 ? "attention" : "neutral"}
          defaultOpen
          action={
            candidates.some((c) => c.admissible) ? (
              <Button
                onClick={() => {
                  candidates.filter((c) => c.admissible).forEach((c) => acceptCandidate(c.id));
                }}
                icon={Check}
                tone="primary"
                title="Accept all detected relationships"
              >
                Accept all ({candidates.filter((c) => c.admissible).length})
              </Button>
            ) : undefined
          }
        >
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            Detected, not applied. Each card shows what was measured and what accepting it will hold
            true from then on.
          </p>
          <div className="flex flex-col gap-2">
            {candidates.map((c) => (
              <CandidateCard key={c.id} candidate={c} />
            ))}
          </div>
        </Group>
      )}

      {started && candidates.length === 0 && (
        <Group id="author.found" title="Found in the drawing" count={0}>
          <Empty
            icon={Sparkles}
            title="Nothing left to propose"
            body="Every relationship the detectors can see is either already in the model or already implied by what is there. Anything else is a design decision, which is the next section."
          />
        </Group>
      )}

      {started && completion && completion.groups.length + completion.quickFixes.length > 0 && (
        <Group
          id="author.decisions"
          title="Decisions to make"
          count={completion.groups.length + completion.quickFixes.length}
          action={
            completion.quickFixes.length > 0 ? (
              <Button
                onClick={() => {
                  completion.quickFixes.forEach((q) => upce.applyIntent(q));
                }}
                icon={Sparkles}
                tone="primary"
                title="Apply all suggested quick fixes"
              >
                Apply all fixes ({completion.quickFixes.length})
              </Button>
            ) : undefined
          }
        >
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            Where more than one answer is valid, the system asks instead of choosing. Every figure
            below was measured by applying the change to a copy and re-checking the constraint system.
          </p>
          {completion.quickFixes.length > 0 && (
            <div className="flex flex-col gap-1.5">
              {completion.quickFixes.map((q) => (
                <IntentOption key={q.id} option={q} />
              ))}
            </div>
          )}
          {completion.groups.map((g) => (
            <div key={g.id} className="flex flex-col gap-1.5">
              <div className="flex items-start gap-1.5">
                <HelpCircle className="w-[12px] h-[12px] mt-[2px] shrink-0 text-(--fg-muted)" strokeWidth={2} />
                <div>
                  <p className="text-[11.5px] text-(--fg-primary) leading-snug">{g.question}</p>
                  <p className="text-[10.5px] text-(--fg-muted)">{g.motion}</p>
                </div>
              </div>
              <div className="flex flex-col gap-1 pl-4">
                {g.blockedBy ? (
                  <p className="text-[10.5px] leading-[1.55] text-(--fg-muted) rounded-[5px] border border-dashed border-(--rule) px-2 py-1.5">
                    {g.blockedBy}
                  </p>
                ) : (
                  g.options.map((o) => <IntentOption key={o.id} option={o} />)
                )}
              </div>
            </div>
          ))}
        </Group>
      )}

      {started && (
        <Group
          id="author.values"
          title="Values"
          defaultOpen
          count={parameters.length}
          action={
            <Button onClick={refreshDerived} icon={Sparkles} tone="quiet" disabled={busy}>
              {busy ? "Testing…" : "Find derived values"}
            </Button>
          }
        >
          {derived.length > 0 && (
            <div className="flex flex-col gap-2">
              {derived.map((d) => (
                <DerivedCard key={d.id} candidate={d} />
              ))}
            </div>
          )}
          {/* A derived value was typed into. Which input should move? */}
          {inversion && (
            <div className="rounded-[6px] border border-(--pen) bg-(--pen-soft) px-2.5 py-2 flex flex-col gap-2">
              <p className="text-[10.5px] leading-[1.5] text-(--fg-primary)">
                <span className="font-mono">{inversion.target}</span> is worked out from other
                values, so it cannot be typed into directly. To make it{" "}
                <span className="font-mono">{inversion.requested}</span>, one of these would change:
              </p>
              <div className="flex flex-col gap-1">
                {inversion.options.map((o) => (
                  <button
                    key={o.parameter}
                    onClick={() => applyInversionOption(o)}
                    className="text-left px-2 py-1.5 rounded-[5px] border border-(--rule) hover:border-(--pen) bg-(--ink-raised) cursor-pointer"
                  >
                    <span className="block text-[11px] text-(--fg-primary) font-mono">
                      {o.parameter}: {o.from.toFixed(1)} → {o.to.toFixed(1)}
                    </span>
                    <span className="block text-[10px] text-(--fg-muted)">{o.note}</span>
                  </button>
                ))}
              </div>
              <Button onClick={dismissInversion} tone="quiet">
                Leave it as it is
              </Button>
            </div>
          )}

          {parameters.length === 0 ? (
            <Empty
              icon={Lock}
              title="No named values yet"
              body="Answering a design question above creates one. Every value that appears here records who created it and why."
            />
          ) : (
            <div className="rounded-[6px] border border-(--rule) overflow-hidden">
              {parameters.map((p) => (
                <ParameterRow key={p.name} parameter={p} />
              ))}
            </div>
          )}

        </Group>
      )}

      {state.cad.components.length > 0 && (
        <Group id="author.component-relations" title="Component relationships" count={state.cad.components.reduce((n, c) => n + (c.relations?.length ?? 0), 0) || undefined}>
          <p className="text-[10.5px] leading-[1.5] text-(--fg-muted)">
            Write your own formula for a placed component: a value follows it instead of being typed, or a new value is worked out and reported. Run mode shows the results, not the formulas.
          </p>
          <ComponentRelationships />
        </Group>
      )}

      {started && <RelationshipsGroup />}

      {started && sketch.constraints.length > 0 && (
        <Group id="author.rules" title="Rules in force" count={sketch.constraints.length}>
          <div className="rounded-[6px] border border-(--rule) overflow-hidden max-h-[260px] overflow-y-auto">
            {sketch.constraints.map((c) => (
              <ConstraintRow key={c.id} id={c.id} />
            ))}
          </div>
        </Group>
      )}

      {started && (
        <Group
          id="author.units"
          title="Units and repeats"
          count={sketch.components.length > 0 ? `${sketch.components.length}` : undefined}
        >
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            A count is not something the solver can solve — it changes how many pieces exist. Changing
            it rebuilds the drawing from the rule, then hands the result to the solver.
          </p>
          <div className="flex items-center gap-1.5">
            <input
              value={componentName}
              onChange={(e) => setComponentName(e.target.value)}
              className="flex-1 min-w-0 h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            />
            <Button
              onClick={() => makeComponent(componentName, selection)}
              icon={Boxes}
              disabled={selection.length === 0}
              title={selection.length === 0 ? "Select the geometry for one unit first" : undefined}
            >
              Make unit
            </Button>
          </div>

          {selection.length === 0 ? (
            <div className="flex flex-col gap-1.5 p-2 rounded bg-(--ink-raised) border border-(--rule)">
              <p className="text-[10.5px] text-(--fg-muted)">
                Select the geometry that makes up one unit — on the canvas, or from the list below.
              </p>
              <div className="flex items-center gap-1.5 flex-wrap">
                <Button
                  onClick={() => selectMultiple(state.shapes.map((s) => s.id))}
                  tone="quiet"
                >
                  Select all ({state.shapes.length})
                </Button>
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-between text-[11px] text-(--fg-secondary) bg-(--ink-raised) border border-(--rule) px-2.5 py-1 rounded">
              <span>{selection.length} shape{selection.length === 1 ? "" : "s"} selected</span>
              <button
                onClick={() => selectMultiple([])}
                className="text-[10px] text-(--fg-muted) hover:text-(--crit) cursor-pointer"
              >
                Clear selection
              </button>
            </div>
          )}

          {/* Interactive Shape Checklist */}
          {state.shapes.length > 0 && (
            <details className="rounded-[6px] border border-(--rule) overflow-hidden">
              <summary className="px-2.5 h-[28px] flex items-center justify-between text-[11px] text-(--fg-muted) cursor-pointer hover:text-(--fg-primary)">
                <span>Choose shapes from list</span>
                <span className="font-mono text-[10px]">{selection.length}/{state.shapes.length}</span>
              </summary>
              <div className="px-2.5 py-2 flex flex-col gap-1 max-h-[160px] overflow-y-auto bg-(--ink-app)">
                {state.shapes.map((s) => {
                  const isChecked = selection.includes(s.id);
                  return (
                    <label
                      key={s.id}
                      className="flex items-center gap-2 text-[10.5px] text-(--fg-secondary) hover:text-(--fg-primary) cursor-pointer"
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={(e) => {
                          if (e.target.checked) {
                            selectMultiple([...selection, s.id]);
                          } else {
                            selectMultiple(selection.filter((id) => id !== s.id));
                          }
                        }}
                      />
                      <span className="font-mono text-[9.5px] uppercase text-(--pen)">{s.type}</span>
                      <span className="truncate">{s.name || s.id}</span>
                    </label>
                  );
                })}
              </div>
            </details>
          )}

          {sketch.components.map((c) => {
            const rule = sketch.repeats.find((r) => r.componentId === c.id);
            const measured = measureUnitFor(c.id, { x: 1, y: 0 });
            const defaultGap = measured?.wall ?? 0;
            const gap = repeatGap ?? defaultGap;
            const report = repeatMeasurements.find((m) => m.ruleId === rule?.id);
            return (
              <div key={c.id} className="rounded-[6px] border border-(--rule) px-2.5 py-2 flex flex-col gap-1.5">
                <p className="text-[11.5px] text-(--fg-primary)">
                  {c.name}
                  <span className="text-(--fg-muted) text-[10px]"> · {c.shapeIds.length} shape(s)</span>
                </p>

                {/* Notebook pages 3 and 5 — a group that is a body, not a label. */}
                <label className="inline-flex items-start gap-1.5 text-[10.5px] text-(--fg-secondary) cursor-pointer">
                  <input
                    type="checkbox"
                    className="mt-[2px]"
                    checked={Boolean(c.rigid)}
                    onChange={(e) => setUnitRigid(c.id, e.target.checked)}
                  />
                  <span>
                    Moves as one piece
                    <span className="block text-(--fg-muted)">
                      {c.rigid
                        ? "Held rigid: three freedoms — across, up, and turn. Nothing inside it can change shape."
                        : "Tie any edge of it to anything and the whole unit follows, instead of that edge pulling away from the rest."}
                    </span>
                  </span>
                </label>

                {measured && measured.extent > 0 && (
                  <p className="text-[10px] text-(--fg-muted) font-mono">
                    {measured.extent.toFixed(1)} across
                    {measured.opening > 0
                      ? ` · opening ${measured.opening.toFixed(1)} · wall ${measured.wall.toFixed(1)}`
                      : " · solid"}
                  </p>
                )}

                {rule ? (
                  <div className="flex flex-col gap-0.5">
                    <p className="text-[10.5px] text-(--fg-muted)">
                      Repeating. Change the count in the values list above.
                    </p>
                    {report && (
                      <p className="text-[10px] text-(--fg-secondary) font-mono">
                        {report.count} x · pitch {report.pitch.toFixed(1)}
                        {report.mode === "gap" && (
                          <span className="text-(--fg-muted)">
                            {" "}
                            = {(report.opening || report.extent).toFixed(1)} + {report.gap.toFixed(1)},
                            measured
                          </span>
                        )}
                      </p>
                    )}
                  </div>
                ) : (
                  <>
                    <div className="flex items-center gap-1.5 text-[10.5px]">
                      <label className="text-(--fg-muted)">count</label>
                      <input
                        type="number"
                        min={1}
                        value={repeatCount}
                        onChange={(e) => setRepeatCount(Number(e.target.value))}
                        className="num w-[46px] h-[22px] px-1 text-right rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none"
                      />
                      <label className="text-(--fg-muted)">
                        {spacingMode === "gap" ? (measured?.opening ? "web" : "gap") : spacingMode === "derived" ? "run" : "pitch"}
                      </label>
                      <input
                        type="number"
                        value={spacingMode === "gap" ? gap : repeatPitch}
                        onChange={(e) =>
                          spacingMode === "gap"
                            ? setRepeatGap(Number(e.target.value))
                            : setRepeatPitch(Number(e.target.value))
                        }
                        className="num w-[64px] h-[22px] px-1 text-right rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none"
                      />
                      <span className="text-(--fg-muted)">mm</span>
                    </div>
                    <div className="flex flex-col gap-0.5 text-[10.5px] text-(--fg-muted)">
                      <label className="inline-flex items-center gap-1.5 cursor-pointer">
                        <input
                          type="radio"
                          checked={spacingMode === "gap"}
                          onChange={() => setSpacingMode("gap")}
                        />
                        hold the material between copies — the pitch follows the unit
                      </label>
                      <label className="inline-flex items-center gap-1.5 cursor-pointer">
                        <input
                          type="radio"
                          checked={spacingMode === "driven"}
                          onChange={() => setSpacingMode("driven")}
                        />
                        keep the pitch fixed — the run grows with the count
                      </label>
                      <label className="inline-flex items-center gap-1.5 cursor-pointer">
                        <input
                          type="radio"
                          checked={spacingMode === "derived"}
                          onChange={() => setSpacingMode("derived")}
                        />
                        keep the overall run fixed — the pitch closes up
                      </label>
                    </div>

                    {spacingMode === "gap" && measured && (
                      <p className="text-[10px] leading-[1.5] text-(--fg-muted)">
                        {measured.opening > 0 ? (
                          <>
                            Pitch will be {measured.opening.toFixed(1)} + {gap.toFixed(1)} ={" "}
                            <span className="text-(--fg-secondary)">
                              {(measured.opening + gap).toFixed(1)} mm
                            </span>
                            , re-measured whenever the unit changes. Starts at {defaultGap.toFixed(1)},
                            which is what already sits between this unit&apos;s opening and its outside.
                          </>
                        ) : (
                          <>
                            This unit encloses nothing, so the gap is measured outside to outside:
                            pitch {measured.extent.toFixed(1)} + {gap.toFixed(1)} ={" "}
                            <span className="text-(--fg-secondary)">
                              {(measured.extent + gap).toFixed(1)} mm
                            </span>
                            .
                          </>
                        )}
                      </p>
                    )}

                    <Button
                      onClick={() =>
                        makeRepeat({
                          componentId: c.id,
                          count: repeatCount,
                          pitch: repeatPitch,
                          gap: spacingMode === "gap" ? gap : undefined,
                          spacingMode,
                          direction: { x: 1, y: 0 },
                        })
                      }
                      icon={Repeat}
                      disabled={spacingMode !== "gap" && repeatPitch <= 0}
                      title={
                        spacingMode !== "gap" && repeatPitch <= 0
                          ? "Set a pitch greater than zero"
                          : undefined
                      }
                    >
                      Repeat it
                    </Button>
                  </>
                )}
              </div>
            );
          })}
        </Group>
      )}

      {/* Notebook page 7 — solids that have run into each other. */}
      {started && overlaps.length > 0 && (
        <Group id="author.overlaps" title="Solids that meet" count={overlaps.length} tone="attention" defaultOpen>
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            Two pours running into each other is a real situation with two real answers: one
            monolithic pour, or a joint between them. Nothing is refused and nothing is rewritten —
            drag them apart and they come apart.
          </p>

          {overlaps.map((o) => (
            <div
              key={`${o.a}|${o.b}`}
              className="rounded-[6px] border border-(--rule) bg-(--ink-raised) px-2.5 py-1.5 text-[10.5px] text-(--fg-secondary)"
            >
              <span className="text-(--fg-primary)">{o.labelA}</span> and{" "}
              <span className="text-(--fg-primary)">{o.labelB}</span> have run into each other by{" "}
              <span className="font-mono">{o.depthMm.toFixed(1)} mm</span>.
            </div>
          ))}

          <label className="inline-flex items-start gap-1.5 text-[10.5px] text-(--fg-secondary) cursor-pointer">
            <input
              type="checkbox"
              className="mt-[2px]"
              checked={sketch.meta.mergeOverlaps !== false}
              onChange={(e) => setMergeOverlaps(e.target.checked)}
            />
            <span>
              Read them as one pour
              <span className="block text-(--fg-muted)">
                The shared material is counted once, and the seam between them is dissolved. Turn
                this off for an expansion joint.
              </span>
            </span>
          </label>

          {fusion && (
            <div className="rounded-[6px] border border-(--rule) overflow-hidden text-[10.5px]">
              <Row label="Pours" value={`${fusion.solids}`} />
              <Row label="Voids kept" value={`${fusion.voids}`} />
              {fusion.merged ? (
                <>
                  <Row
                    label="Shared material"
                    value={`${((fusion.grossAreaMm2 - fusion.netAreaMm2) / 1e6).toFixed(4)} m²`}
                  />
                  <Row label="Counted once" value={`${(fusion.netAreaMm2 / 1e6).toFixed(4)} m²`} />
                </>
              ) : (
                <Row
                  label="Counted separately"
                  value={`${(fusion.grossAreaMm2 / 1e6).toFixed(4)} m²`}
                />
              )}
              {fusion.webs.map((w) => (
                <Row
                  key={w.between.join("|")}
                  label="Web after merge"
                  value={`${w.thickness.toFixed(1)} mm`}
                />
              ))}
            </div>
          )}
        </Group>
      )}

      {started && (
        <Group id="author.publish" title="Publish">
          <input
            value={sketch.meta.name}
            onChange={(e) => setTemplateName(e.target.value)}
            className="h-[26px] px-2 text-[11.5px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
          />
          <div className="flex items-center gap-1.5">
            <Button onClick={checkReadiness} icon={ClipboardCheck} disabled={busy}>
              {busy ? "Checking…" : "Check it"}
            </Button>
            <Button onClick={publishTemplate} icon={Upload} tone="primary" disabled={!readiness?.ready}>
              Publish
            </Button>
          </div>

          {readiness && (
            <div className="rounded-[6px] border border-(--rule) overflow-hidden">
              {readiness.checks.map((c) => (
                <div key={c.label} className="px-2.5 py-1.5 border-t border-(--rule) first:border-t-0 flex gap-2">
                  <span className="shrink-0 mt-[2px]">
                    {c.status === "pass" ? (
                      <CircleCheck className="w-[12px] h-[12px] text-(--ok)" strokeWidth={2.2} />
                    ) : c.status === "warn" ? (
                      <TriangleAlert className="w-[12px] h-[12px] text-(--warn)" strokeWidth={2.2} />
                    ) : (
                      <CircleX className="w-[12px] h-[12px] text-(--crit)" strokeWidth={2.2} />
                    )}
                  </span>
                  <span className="flex-1 min-w-0">
                    <span className="block text-[11px] text-(--fg-primary)">{c.label}</span>
                    <span className="block text-[10.5px] leading-[1.5] text-(--fg-muted)">{c.detail}</span>
                  </span>
                </div>
              ))}
              {readiness.sweep.length > 0 && (
                <div className="px-2.5 py-1.5 border-t border-(--rule) bg-(--ink-sunken) text-[10.5px] text-(--fg-muted)">
                  {readiness.sweep.filter((s) => s.ok).length} of {readiness.sweep.length} test values
                  re-solved with every declared relationship intact.
                </div>
              )}
            </div>
          )}

          {manifest && (
            <div className="rounded-[6px] border border-(--ok) bg-(--ok-soft) px-2.5 py-2">
              <p className="text-[11.5px] text-(--ok) font-medium">
                {manifest.name} v{manifest.version} published
              </p>
              <p className="text-[10.5px] text-(--fg-secondary) mt-0.5">
                Switch the persona to Run to use it as a project engineer would: {manifest.driving.length}{" "}
                value{manifest.driving.length === 1 ? "" : "s"} to type, {manifest.derived.length} worked
                out for them.
              </p>
            </div>
          )}
        </Group>
      )}
    </div>
  );
}
