"use client";

/**
 * The AUTHOR dock — the draftsman's parametric authoring workflow.
 *
 * The panel is ordered the way the work is actually done, not the way the
 * architecture is layered:
 *
 *     analyse  ->  review what was found  ->  see what is still free
 *              ->  answer the design questions  ->  name the values
 *              ->  group and repeat  ->  check  ->  publish
 *
 * Two rules from the brief are visible in every section below:
 *
 *   §3.3  a candidate says what was detected, from which measurements, how far
 *         off it is, and what accepting it will preserve. Nothing is applied
 *         until the author presses Accept.
 *
 *   §13   the author must be able to tell apart a measured fact, an accepted
 *         inference, a driving value, a derived value and a system default —
 *         so every parameter row carries its origin, and every derived value
 *         can be asked "why do you exist?".
 */

import React from "react";
import {
  Check,
  X,
  Sparkles,
  Scan,
  HelpCircle,
  Lock,
  ChevronRight,
  Boxes,
  Repeat,
  ClipboardCheck,
  Upload,
  Undo2,
  Info,
  TriangleAlert,
  CircleCheck,
  CircleX,
  Trash2,
  Eye,
  EyeOff,
} from "lucide-react";
import { useDrawing } from "@/lib/state/drawingContext";
import { useUpce } from "../parametric/upceContext";
import { PanelBody, Empty } from "./DraftPanel";
import type { ConstraintCandidate, DerivedCandidate, SketchParameter } from "@/lib/upce/types";
import type { IntentAction } from "@/lib/upce/completion";

const ORIGIN_LABEL: Record<string, string> = {
  "geometric-fact": "Part of the shape",
  "inference-accepted": "Detected, then accepted",
  user: "You created this",
  "completion-assistant": "Chosen from a suggestion",
  template: "Came with the template",
  component: "Generated by a repeat",
};

const ROLE_TONE: Record<string, string> = {
  DRIVING: "bg-(--pen-soft) text-(--pen)",
  DERIVED: "bg-(--ink-sunken) text-(--dim-derived)",
  FIXED: "bg-(--ink-sunken) text-(--fg-muted)",
  MEASURED: "bg-(--ink-sunken) text-(--fg-muted)",
};

function Section({
  title,
  count,
  children,
  action,
}: {
  title: string;
  count?: number | string;
  children: React.ReactNode;
  action?: React.ReactNode;
}) {
  return (
    <section className="flex flex-col gap-2">
      <div className="flex items-center justify-between gap-2">
        <h3 className="label">{title}</h3>
        <div className="flex items-center gap-2">
          {count !== undefined && (
            <span className="num text-[10px] text-(--fg-muted)">{count}</span>
          )}
          {action}
        </div>
      </div>
      {children}
    </section>
  );
}

function Button({
  onClick,
  children,
  icon: Icon,
  tone = "default",
  disabled,
  title,
}: {
  onClick: () => void;
  children: React.ReactNode;
  icon?: typeof Scan;
  tone?: "default" | "primary" | "quiet";
  disabled?: boolean;
  title?: string;
}) {
  const cls =
    tone === "primary"
      ? "bg-(--pen) text-(--ink-app) hover:opacity-90"
      : tone === "quiet"
        ? "text-(--fg-muted) hover:text-(--fg-primary) hover:bg-(--ink-raised)"
        : "border border-(--rule) text-(--fg-secondary) hover:text-(--fg-primary) hover:border-(--rule-strong)";
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      title={title}
      className={`h-[26px] px-2.5 rounded-[5px] text-[11.5px] font-medium inline-flex items-center gap-1.5 transition-colors duration-100 cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed ${cls}`}
    >
      {Icon && <Icon className="w-[12px] h-[12px]" strokeWidth={2.1} />}
      {children}
    </button>
  );
}

// ---------------------------------------------------------------------------

function NoticeBar() {
  const { notice, dismissNotice } = useUpce();
  if (!notice) return null;
  const tone =
    notice.kind === "error"
      ? "border-(--crit) bg-(--crit-soft) text-(--crit)"
      : notice.kind === "warn"
        ? "border-(--warn) bg-(--warn-soft) text-(--warn)"
        : notice.kind === "ok"
          ? "border-(--ok) bg-(--ok-soft) text-(--ok)"
          : "border-(--rule) bg-(--ink-raised) text-(--fg-secondary)";
  const Icon =
    notice.kind === "error" ? CircleX : notice.kind === "warn" ? TriangleAlert : notice.kind === "ok" ? CircleCheck : Info;
  return (
    <div className={`rounded-[6px] border px-2.5 py-2 flex items-start gap-2 ${tone}`}>
      <Icon className="w-[13px] h-[13px] mt-[1px] shrink-0" strokeWidth={2.1} />
      <p className="text-[11px] leading-[1.5] flex-1">{notice.text}</p>
      <button onClick={dismissNotice} className="shrink-0 cursor-pointer opacity-60 hover:opacity-100">
        <X className="w-[11px] h-[11px]" strokeWidth={2.4} />
      </button>
    </div>
  );
}

function CandidateCard({ candidate }: { candidate: ConstraintCandidate }) {
  const { acceptCandidate, rejectCandidate } = useUpce();
  const [open, setOpen] = React.useState(false);

  return (
    <article
      className={`rounded-[7px] border overflow-hidden ${
        candidate.admissible ? "border-(--rule) bg-(--ink-raised)" : "border-(--crit) bg-(--crit-soft)"
      }`}
    >
      <div className="px-2.5 pt-2 pb-2 flex flex-col gap-1.5">
        <p className="text-[12px] font-medium text-(--fg-primary) leading-snug">{candidate.headline}</p>

        <p className="text-[11px] leading-[1.5] text-(--fg-secondary)">{candidate.evidence[0]}</p>

        <div className="flex items-center gap-2 text-[10px] text-(--fg-muted)">
          <span>off by {candidate.deviation}</span>
          <span className="w-px h-[9px] bg-(--rule)" aria-hidden="true" />
          {candidate.admissible ? (
            <span>removes {candidate.dofRemoved} degree{candidate.dofRemoved === 1 ? "" : "s"} of freedom</span>
          ) : (
            <span className="text-(--crit)">{candidate.admissibilityNote}</span>
          )}
          {candidate.impliedCount ? (
            <>
              <span className="w-px h-[9px] bg-(--rule)" aria-hidden="true" />
              <span>settles {candidate.impliedCount} more like it</span>
            </>
          ) : null}
        </div>

        <button
          onClick={() => setOpen((v) => !v)}
          className="text-[10.5px] text-(--fg-muted) hover:text-(--fg-secondary) inline-flex items-center gap-1 self-start cursor-pointer"
        >
          <ChevronRight
            className={`w-[10px] h-[10px] transition-transform ${open ? "rotate-90" : ""}`}
            strokeWidth={2.2}
          />
          {open ? "Less" : "Why, and what it preserves"}
        </button>

        {open && (
          <div className="flex flex-col gap-1 pl-3 border-l border-(--rule) text-[10.5px] leading-[1.55] text-(--fg-muted)">
            {candidate.evidence.map((e, i) => (
              <p key={i}>{e}</p>
            ))}
            <p className="text-(--fg-secondary)">If you accept: {candidate.preserves}</p>
            <p>Affects {candidate.affectedShapeIds.join(", ")}.</p>
          </div>
        )}
      </div>

      {candidate.admissible && (
        <div className="flex border-t border-(--rule)">
          <button
            onClick={() => acceptCandidate(candidate.id)}
            className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--ok) hover:bg-(--ok-soft) cursor-pointer"
          >
            <Check className="w-[12px] h-[12px]" strokeWidth={2.4} />
            Accept
          </button>
          <div className="w-px bg-(--rule)" aria-hidden="true" />
          <button
            onClick={() => rejectCandidate(candidate.id)}
            className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--fg-muted) hover:bg-(--crit-soft) hover:text-(--crit) cursor-pointer"
          >
            <X className="w-[12px] h-[12px]" strokeWidth={2.4} />
            Not intended
          </button>
        </div>
      )}
    </article>
  );
}

function IntentOption({ option }: { option: IntentAction }) {
  const { applyIntent } = useUpce();
  const [open, setOpen] = React.useState(false);
  return (
    <div className="rounded-[6px] border border-(--rule) bg-(--ink-raised) overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full px-2.5 py-2 flex items-start gap-2 text-left cursor-pointer hover:bg-(--ink-sunken)"
      >
        <ChevronRight
          className={`w-[11px] h-[11px] mt-[2px] shrink-0 text-(--fg-muted) transition-transform ${open ? "rotate-90" : ""}`}
          strokeWidth={2.2}
        />
        <span className="flex-1 min-w-0">
          <span className="block text-[11.5px] text-(--fg-primary) leading-snug">{option.title}</span>
          <span className="block text-[10px] text-(--fg-muted) mt-0.5">
            {option.isDeliberateFreedom
              ? "leaves it free on purpose"
              : `removes ${option.dofRemoved} degree${option.dofRemoved === 1 ? "" : "s"} of freedom`}
            {option.createsParameters.length > 0 &&
              ` · creates ${option.createsParameters.map((p) => p.name).join(", ")}`}
          </span>
        </span>
      </button>
      {open && (
        <div className="px-2.5 pb-2 flex flex-col gap-1.5">
          <p className="text-[10.5px] leading-[1.55] text-(--fg-secondary)">{option.rationale}</p>
          {option.evidence.map((e, i) => (
            <p key={i} className="text-[10.5px] text-(--fg-muted)">
              {e}
            </p>
          ))}
          <Button onClick={() => applyIntent(option)} tone="primary">
            {option.isDeliberateFreedom ? "That is intended" : "This is what I meant"}
          </Button>
        </div>
      )}
    </div>
  );
}

function DerivedCard({ candidate }: { candidate: DerivedCandidate }) {
  const { acceptDerivedCandidate, rejectDerivedCandidate } = useUpce();
  return (
    <article className="rounded-[7px] border border-(--rule) bg-(--ink-raised) overflow-hidden">
      <div className="px-2.5 pt-2 pb-2 flex flex-col gap-1.5">
        <div className="flex items-baseline justify-between gap-2">
          <span className="text-[12px] font-medium text-(--fg-primary)">{candidate.name}</span>
          <span className="num text-[12px] text-(--fg-primary)">
            {candidate.value.toFixed(1)}
            <span className="text-(--fg-muted) ml-1 text-[10px]">mm</span>
          </span>
        </div>
        <p className="text-[11px] leading-[1.5] text-(--fg-secondary)">{candidate.headline}</p>
        <code className="num text-[10.5px] text-(--fg-muted) bg-(--ink-sunken) rounded px-1.5 py-1 overflow-x-auto whitespace-nowrap">
          {candidate.name} = {candidate.expr}
        </code>
        <div className="flex flex-col gap-0.5 text-[10px] text-(--fg-muted)">
          {candidate.evidence.map((e, i) => (
            <span key={i}>{e}</span>
          ))}
        </div>
      </div>
      <div className="flex border-t border-(--rule)">
        <button
          onClick={() => acceptDerivedCandidate(candidate.id)}
          className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--ok) hover:bg-(--ok-soft) cursor-pointer"
        >
          <Check className="w-[12px] h-[12px]" strokeWidth={2.4} />
          Keep it
        </button>
        <div className="w-px bg-(--rule)" aria-hidden="true" />
        <button
          onClick={() => rejectDerivedCandidate(candidate.id)}
          className="flex-1 h-[28px] flex items-center justify-center gap-1.5 text-[11px] font-medium text-(--fg-muted) hover:bg-(--crit-soft) hover:text-(--crit) cursor-pointer"
        >
          <X className="w-[12px] h-[12px]" strokeWidth={2.4} />
          Discard
        </button>
      </div>
    </article>
  );
}

function ParameterRow({ parameter }: { parameter: SketchParameter }) {
  const { setParameterValue, updateParameter, renameParameter, dependentsFor, sketch, createDerivedParameter } = useUpce();
  const [open, setOpen] = React.useState(false);
  const [draft, setDraft] = React.useState(String(parameter.value));
  const [nameDraft, setNameDraft] = React.useState(parameter.name);
  const [editingName, setEditingName] = React.useState(false);

  React.useEffect(() => setDraft(String(parameter.value)), [parameter.value]);

  const dependents = dependentsFor(parameter.name);
  const drives = parameter.boundConstraints
    .map((id) => sketch.constraints.find((c) => c.id === id)?.label)
    .filter(Boolean) as string[];

  return (
    <div className="border-t border-(--rule) first:border-t-0">
      <div className="flex items-center gap-2 px-2.5 h-[32px]">
        <span
          className={`text-[9px] px-1 rounded-sm font-semibold tracking-wide ${ROLE_TONE[parameter.role]}`}
        >
          {parameter.role.slice(0, 3)}
        </span>
        {editingName ? (
          <input
            autoFocus
            value={nameDraft}
            onChange={(e) => setNameDraft(e.target.value)}
            onBlur={() => {
              setEditingName(false);
              renameParameter(parameter.name, nameDraft);
            }}
            onKeyDown={(e) => e.key === "Enter" && e.currentTarget.blur()}
            className="flex-1 min-w-0 h-[20px] px-1 text-[11.5px] bg-(--ink-sunken) border border-(--pen) rounded-[3px] outline-none text-(--fg-primary)"
          />
        ) : (
          <button
            onDoubleClick={() => setEditingName(true)}
            onClick={() => setOpen((v) => !v)}
            title="Double-click to rename"
            className="flex-1 min-w-0 text-left text-[11.5px] text-(--fg-secondary) truncate cursor-pointer hover:text-(--fg-primary)"
          >
            {parameter.name}
          </button>
        )}
        {parameter.role === "DRIVING" ? (
          <input
            value={draft}
            inputMode="decimal"
            onChange={(e) => setDraft(e.target.value)}
            onBlur={() => {
              const v = Number(draft);
              if (Number.isFinite(v) && v !== parameter.value) setParameterValue(parameter.name, v);
              else setDraft(String(parameter.value));
            }}
            onKeyDown={(e) => {
              if (e.key === "Enter") (e.target as HTMLInputElement).blur();
              if (e.key === "Escape") {
                setDraft(String(parameter.value));
                e.currentTarget.blur();
              }
            }}
            className="num w-[64px] h-[22px] px-1.5 text-right text-[11.5px] bg-(--ink-raised) border border-(--rule) rounded-[3px] outline-none focus:border-(--pen) text-(--fg-primary)"
          />
        ) : (
          <span className="num text-[11.5px] text-(--fg-muted) inline-flex items-center gap-1">
            <Lock className="w-[9px] h-[9px]" strokeWidth={2.2} />
            {parameter.value.toFixed(1)}
          </span>
        )}
        <span className="text-[9.5px] text-(--fg-muted) w-[24px]">{parameter.unit}</span>
      </div>

      {open && (
        <div className="px-2.5 pb-2.5 pt-0.5 flex flex-col gap-1.5 text-[10.5px] leading-[1.55]">
          <p className="text-(--fg-secondary)">
            <span className="text-(--fg-muted)">Origin · </span>
            {ORIGIN_LABEL[parameter.provenance.origin] ?? parameter.provenance.origin}
          </p>
          <p className="text-(--fg-muted)">{parameter.provenance.detail}</p>
          
          <div className="flex items-center gap-1.5 pt-1">
            <label className="text-(--fg-muted) shrink-0">Formula</label>
            <input
              key={parameter.expr ?? ""}
              defaultValue={parameter.expr ?? ""}
              placeholder="e.g. CellCount * CellPitch + 30"
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
              }}
              onBlur={(e) => {
                const expr = e.target.value.trim();
                if (expr && expr !== parameter.expr) {
                  createDerivedParameter(parameter.name, expr);
                } else if (!expr && parameter.expr) {
                  updateParameter(parameter.name, { role: "DRIVING", expr: undefined, dependencies: [] });
                }
              }}
              className="num flex-1 h-[22px] px-1.5 text-[10.5px] rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            />
          </div>

          {drives.length > 0 && (
            <div>
              <p className="text-(--fg-secondary)">Changing it moves:</p>
              <ul className="list-none pl-2">
                {drives.map((d, i) => (
                  <li key={i} className="text-(--fg-muted)">
                    · {d}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {dependents.length > 0 && (
            <p className="text-(--fg-muted)">Other values that follow it: {dependents.join(", ")}</p>
          )}
          <div className="flex items-center gap-2 pt-1">
            <label className="text-(--fg-muted)">Range</label>
            <input
              defaultValue={parameter.min ?? ""}
              placeholder="min"
              onBlur={(e) =>
                updateParameter(parameter.name, {
                  min: e.target.value === "" ? undefined : Number(e.target.value),
                })
              }
              className="num w-[52px] h-[20px] px-1 text-right text-[10.5px] rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen)"
            />
            <input
              defaultValue={parameter.max ?? ""}
              placeholder="max"
              onBlur={(e) =>
                updateParameter(parameter.name, {
                  max: e.target.value === "" ? undefined : Number(e.target.value),
                })
              }
              className="num w-[52px] h-[20px] px-1 text-right text-[10.5px] rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen)"
            />
            <label className="ml-auto inline-flex items-center gap-1 cursor-pointer text-(--fg-muted)">
              <input
                type="checkbox"
                checked={parameter.published}
                onChange={(e) => updateParameter(parameter.name, { published: e.target.checked })}
              />
              show to users
            </label>
          </div>
        </div>
      )}
    </div>
  );
}

function ConstraintRow({ id }: { id: string }) {
  const { sketch, deleteConstraint, toggleConstraint } = useUpce();
  const c = sketch.constraints.find((x) => x.id === id);
  const [open, setOpen] = React.useState(false);
  if (!c) return null;
  const isFact = c.strength === "fact";
  const suppressed = c.state === "suppressed";

  return (
    <div className="border-t border-(--rule) first:border-t-0">
      <div className="flex items-center gap-1.5 px-2.5 min-h-[28px] py-1">
        <button
          onClick={() => setOpen((v) => !v)}
          className={`flex-1 min-w-0 text-left text-[11px] leading-snug cursor-pointer ${
            suppressed ? "text-(--fg-muted) line-through" : "text-(--fg-secondary) hover:text-(--fg-primary)"
          }`}
        >
          {c.label}
          {c.paramRef && <span className="text-(--pen)"> = {c.paramRef}</span>}
        </button>
        <button
          onClick={() => toggleConstraint(c.id)}
          title={suppressed ? "Switch back on" : "Switch off temporarily"}
          className="shrink-0 w-[20px] h-[20px] grid place-items-center rounded text-(--fg-muted) hover:text-(--fg-primary) cursor-pointer disabled:opacity-30"
          disabled={isFact}
        >
          {suppressed ? <EyeOff className="w-[11px] h-[11px]" /> : <Eye className="w-[11px] h-[11px]" />}
        </button>
        <button
          onClick={() => deleteConstraint(c.id)}
          title={isFact ? "Part of the shape — cannot be removed here" : "Remove"}
          disabled={isFact}
          className="shrink-0 w-[20px] h-[20px] grid place-items-center rounded text-(--fg-muted) hover:text-(--crit) cursor-pointer disabled:opacity-30"
        >
          <Trash2 className="w-[11px] h-[11px]" />
        </button>
      </div>
      {open && (
        <p className="px-2.5 pb-2 text-[10.5px] leading-[1.55] text-(--fg-muted)">
          <span className="text-(--fg-secondary)">
            {ORIGIN_LABEL[c.provenance.origin] ?? c.provenance.origin} ·{" "}
          </span>
          {c.provenance.detail}
          {c.provenance.evidence?.length ? ` (${c.provenance.evidence.join("; ")})` : ""}
        </p>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------

export function AuthorPanel() {
  const { state, dispatch, selectedShapes, selectMultiple } = useDrawing();
  const upce = useUpce();
  const {
    started,
    sketch,
    dof,
    candidates,
    derived,
    completion,
    readiness,
    manifest,
    busy,
    analyse,
    acceptCandidate,
    refreshDerived,
    makeComponent,
    makeRepeat,
    setIntentionalFreedom,
    setTemplateName,
    checkReadiness,
    publishTemplate,
    undoIntent,
    canUndoIntent,
  } = upce;

  const parameters = Object.values(sketch.parameters);
  const selection = state.selectedIds.length > 0 ? state.selectedIds : state.selectedId ? [state.selectedId] : [];

  const [componentName, setComponentName] = React.useState("Unit");
  const [repeatCount, setRepeatCount] = React.useState(3);
  const [repeatPitch, setRepeatPitch] = React.useState(0);
  const [spacingMode, setSpacingMode] = React.useState<"driven" | "derived">("driven");
  const [formulaName, setFormulaName] = React.useState("");
  const [formulaExpr, setFormulaExpr] = React.useState("");

  return (
    <PanelBody>
      <NoticeBar />

      {/* Selected Entity Inspector Banner in Author Mode */}
      {selectedShapes.length > 0 && (
        <div className="rounded-[6px] border border-(--rule) bg-(--ink-raised) p-2.5 flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-semibold text-(--fg-primary) flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-(--pen)" />
              Selected: {selectedShapes.length === 1 ? selectedShapes[0].type : `${selectedShapes.length} shapes`}
            </span>
            {selectedShapes.length === 1 && (
              <span className="text-[10px] text-(--pen) font-mono bg-(--ink-sunken) px-1.5 py-0.5 rounded border border-(--rule) max-w-[130px] truncate" title={selectedShapes[0].id}>
                {selectedShapes[0].id}
              </span>
            )}
          </div>

          {selectedShapes.length === 1 ? (
            <div className="flex items-center gap-2">
              <label className="text-[11px] font-medium text-(--fg-muted) shrink-0">Name:</label>
              <input
                value={selectedShapes[0].name ?? ""}
                placeholder="Give this shape a name (e.g. Outer_Frame, Cell_Roof)"
                onChange={(e) =>
                  dispatch({
                    type: "UPDATE_SHAPE",
                    id: selectedShapes[0].id,
                    updates: { name: e.target.value },
                  })
                }
                className="flex-1 min-w-0 h-[24px] px-2 text-[11.5px] rounded-[4px] bg-(--ink-sunken) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary) font-mono"
              />
            </div>
          ) : (
            <div className="flex flex-wrap gap-1">
              {selectedShapes.map((s) => (
                <span key={s.id} className="text-[10px] bg-(--ink-sunken) border border-(--rule) px-1.5 py-0.5 rounded text-(--fg-secondary) font-mono">
                  {s.name || s.type}
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      <Section
        title="Step 1 · Read the drawing"
        action={
          canUndoIntent ? (
            <Button onClick={undoIntent} icon={Undo2} tone="quiet" title="Step back one design decision">
              Step back
            </Button>
          ) : undefined
        }
      >
        <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
          Nothing is changed by this. The drawing is measured, relationships are proposed, and the
          remaining freedom is worked out from the constraint system itself.
        </p>
        <Button onClick={analyse} icon={Scan} tone="primary">
          Analyse geometry
        </Button>
      </Section>

      {started && dof && (
        <Section title="What is still free" count={`${dof.dof} DOF`}>
          <div className="rounded-[6px] border border-(--rule) overflow-hidden">
            <div
              className={`px-2.5 py-2 text-[11.5px] font-medium ${
                dof.status === "well"
                  ? "bg-(--ok-soft) text-(--ok)"
                  : dof.status === "over"
                    ? "bg-(--crit-soft) text-(--crit)"
                    : "bg-(--ink-sunken) text-(--fg-secondary)"
              }`}
            >
              {dof.status === "well"
                ? "Fully defined — nothing can move on its own"
                : dof.status === "over"
                  ? "Requirements conflict"
                  : `Under-defined — ${dof.dof} independent movement${dof.dof === 1 ? "" : "s"} remain`}
            </div>
            {dof.motions.length > 0 && (
              <ul className="px-2.5 py-2 flex flex-col gap-1">
                {dof.motions.map((m, i) => (
                  <li key={i} className="text-[11px] leading-[1.5] text-(--fg-secondary)">
                    · {m.description}
                  </li>
                ))}
              </ul>
            )}
            {dof.diagnoses.filter((d) => d.status !== "active").map((d) => (
              <div
                key={d.constraintId}
                className={`px-2.5 py-1.5 border-t border-(--rule) text-[10.5px] leading-[1.5] ${
                  d.status === "conflicting" ? "text-(--crit)" : "text-(--fg-muted)"
                }`}
              >
                <span className="font-medium">{d.label}</span> — {d.note}
              </div>
            ))}
          </div>
          {dof.dof > 0 && (
            <label className="flex items-center gap-1.5 text-[10.5px] text-(--fg-muted) cursor-pointer">
              <input
                type="checkbox"
                checked={sketch.meta.freedomIsIntentional}
                onChange={(e) => setIntentionalFreedom(e.target.checked)}
              />
              This freedom is intended — do not treat it as unfinished
            </label>
          )}
        </Section>
      )}

      {started && candidates.length > 0 && (
        <Section
          title="Step 2 · Relationships found"
          count={candidates.length}
          action={
            candidates.some((c) => c.admissible) ? (
              <Button
                onClick={() => {
                  candidates.filter((c) => c.admissible).forEach((c) => acceptCandidate(c.id));
                }}
                icon={Check}
                tone="primary"
                title="Accept all detected relationships"
              >
                Accept all ({candidates.filter((c) => c.admissible).length})
              </Button>
            ) : undefined
          }
        >
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            Detected, not applied. Each card shows what was measured and what accepting it will hold
            true from then on.
          </p>
          <div className="flex flex-col gap-2">
            {candidates.map((c) => (
              <CandidateCard key={c.id} candidate={c} />
            ))}
          </div>
        </Section>
      )}

      {started && candidates.length === 0 && (
        <Section title="Step 2 · Relationships found" count={0}>
          <Empty
            icon={Sparkles}
            title="Nothing left to propose"
            body="Every relationship the detectors can see is either already in the model or already implied by what is there. Anything else is a design decision, which is the next section."
          />
        </Section>
      )}

      {started && completion && completion.groups.length + completion.quickFixes.length > 0 && (
        <Section
          title="Step 3 · Decide the design"
          count={completion.groups.length + completion.quickFixes.length}
          action={
            completion.quickFixes.length > 0 ? (
              <Button
                onClick={() => {
                  completion.quickFixes.forEach((q) => upce.applyIntent(q));
                }}
                icon={Sparkles}
                tone="primary"
                title="Apply all suggested quick fixes"
              >
                Apply all fixes ({completion.quickFixes.length})
              </Button>
            ) : undefined
          }
        >
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            Where more than one answer is valid, the system asks instead of choosing. Every figure
            below was measured by applying the change to a copy and re-checking the constraint system.
          </p>
          {completion.quickFixes.length > 0 && (
            <div className="flex flex-col gap-1.5">
              {completion.quickFixes.map((q) => (
                <IntentOption key={q.id} option={q} />
              ))}
            </div>
          )}
          {completion.groups.map((g) => (
            <div key={g.id} className="flex flex-col gap-1.5">
              <div className="flex items-start gap-1.5">
                <HelpCircle className="w-[12px] h-[12px] mt-[2px] shrink-0 text-(--fg-muted)" strokeWidth={2} />
                <div>
                  <p className="text-[11.5px] text-(--fg-primary) leading-snug">{g.question}</p>
                  <p className="text-[10.5px] text-(--fg-muted)">{g.motion}</p>
                </div>
              </div>
              <div className="flex flex-col gap-1 pl-4">
                {g.options.map((o) => (
                  <IntentOption key={o.id} option={o} />
                ))}
              </div>
            </div>
          ))}
        </Section>
      )}

      {started && (
        <Section
          title="Step 4 · Values"
          count={parameters.length}
          action={
            <Button onClick={refreshDerived} icon={Sparkles} tone="quiet" disabled={busy}>
              {busy ? "Testing…" : "Find derived values"}
            </Button>
          }
        >
          {derived.length > 0 && (
            <div className="flex flex-col gap-2">
              {derived.map((d) => (
                <DerivedCard key={d.id} candidate={d} />
              ))}
            </div>
          )}
          {parameters.length === 0 ? (
            <Empty
              icon={Lock}
              title="No named values yet"
              body="Answering a design question above creates one. Every value that appears here records who created it and why."
            />
          ) : (
            <div className="rounded-[6px] border border-(--rule) overflow-hidden">
              {parameters.map((p) => (
                <ParameterRow key={p.name} parameter={p} />
              ))}
            </div>
          )}

          <details className="rounded-[6px] border border-(--rule) overflow-hidden">
            <summary className="px-2.5 h-[28px] flex items-center text-[11px] text-(--fg-muted) cursor-pointer">
              Write a relationship myself
            </summary>
            <div className="px-2.5 py-2 flex flex-col gap-1.5">
              <p className="text-[10.5px] leading-[1.5] text-(--fg-muted)">
                For the cases the detectors cannot see. The expression is parsed, its references are
                checked against real parameters, and a circular definition is refused before it is saved.
              </p>
              <div className="flex items-center gap-1.5">
                <input
                  value={formulaName}
                  onChange={(e) => setFormulaName(e.target.value)}
                  placeholder="Name"
                  className="w-[86px] h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
                />
                <span className="text-(--fg-muted) text-[11px]">=</span>
                <input
                  value={formulaExpr}
                  onChange={(e) => setFormulaExpr(e.target.value)}
                  placeholder="OuterWidth - 2 * WallThickness"
                  className="num flex-1 min-w-0 h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
                />
              </div>
              <Button
                onClick={() => {
                  upce.createDerivedParameter(formulaName, formulaExpr);
                  setFormulaName("");
                  setFormulaExpr("");
                }}
                disabled={!formulaName.trim() || !formulaExpr.trim()}
              >
                Check and add
              </Button>
            </div>
          </details>
        </Section>
      )}

      {started && sketch.constraints.length > 0 && (
        <Section title="Rules in force" count={sketch.constraints.length}>
          <div className="rounded-[6px] border border-(--rule) overflow-hidden max-h-[260px] overflow-y-auto">
            {sketch.constraints.map((c) => (
              <ConstraintRow key={c.id} id={c.id} />
            ))}
          </div>
        </Section>
      )}

      {started && (
        <Section title="Step 5 · Reuse and repeat" count={`${sketch.components.length}/${sketch.repeats.length}`}>
          <p className="text-[11px] leading-[1.55] text-(--fg-muted)">
            A count is not something the solver can solve — it changes how many pieces exist. Changing
            it rebuilds the drawing from the rule, then hands the result to the solver.
          </p>
          <div className="flex items-center gap-1.5">
            <input
              value={componentName}
              onChange={(e) => setComponentName(e.target.value)}
              className="flex-1 min-w-0 h-[24px] px-1.5 text-[11px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
            />
            <Button
              onClick={() => makeComponent(componentName, selection)}
              icon={Boxes}
              disabled={selection.length === 0}
              title={selection.length === 0 ? "Select the geometry for one unit first" : undefined}
            >
              Make unit
            </Button>
          </div>

          {selection.length === 0 ? (
            <div className="flex flex-col gap-1.5 p-2 rounded bg-(--ink-raised) border border-(--rule)">
              <p className="text-[10.5px] text-(--fg-muted)">
                Select shapes on canvas, or click to auto-select inner cell shapes:
              </p>
              <div className="flex items-center gap-1.5 flex-wrap">
                <Button
                  onClick={() => {
                    // Filter out the outer enclosing rectangle
                    const rects = state.shapes.filter((s) => s.type === "rectangle") as { id: string; width?: number; height?: number }[];
                    let outerId: string | null = null;
                    if (rects.length > 0) {
                      const largest = rects.reduce((prev, curr) =>
                        ((curr.width ?? 0) * (curr.height ?? 0)) > ((prev.width ?? 0) * (prev.height ?? 0)) ? curr : prev
                      );
                      outerId = largest.id;
                    }
                    const innerShapes = state.shapes.filter((s) => s.id !== outerId);
                    selectMultiple(innerShapes.map((s) => s.id));
                  }}
                  tone="quiet"
                >
                  + Select cell shapes ({state.shapes.length > 1 ? state.shapes.length - 1 : state.shapes.length})
                </Button>
                <Button
                  onClick={() => selectMultiple(state.shapes.map((s) => s.id))}
                  tone="quiet"
                >
                  Select all
                </Button>
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-between text-[11px] text-(--fg-secondary) bg-(--ink-raised) border border-(--rule) px-2.5 py-1 rounded">
              <span>{selection.length} shape{selection.length === 1 ? "" : "s"} selected</span>
              <button
                onClick={() => selectMultiple([])}
                className="text-[10px] text-(--fg-muted) hover:text-(--crit) cursor-pointer"
              >
                Clear selection
              </button>
            </div>
          )}

          {/* Interactive Shape Checklist */}
          {state.shapes.length > 0 && (
            <details className="rounded-[6px] border border-(--rule) overflow-hidden">
              <summary className="px-2.5 h-[28px] flex items-center justify-between text-[11px] text-(--fg-muted) cursor-pointer hover:text-(--fg-primary)">
                <span>Choose shapes from list</span>
                <span className="font-mono text-[10px]">{selection.length}/{state.shapes.length}</span>
              </summary>
              <div className="px-2.5 py-2 flex flex-col gap-1 max-h-[160px] overflow-y-auto bg-(--ink-app)">
                {state.shapes.map((s) => {
                  const isChecked = selection.includes(s.id);
                  return (
                    <label
                      key={s.id}
                      className="flex items-center gap-2 text-[10.5px] text-(--fg-secondary) hover:text-(--fg-primary) cursor-pointer"
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={(e) => {
                          if (e.target.checked) {
                            selectMultiple([...selection, s.id]);
                          } else {
                            selectMultiple(selection.filter((id) => id !== s.id));
                          }
                        }}
                      />
                      <span className="font-mono text-[9.5px] uppercase text-(--pen)">{s.type}</span>
                      <span className="truncate">{s.name || s.id}</span>
                    </label>
                  );
                })}
              </div>
            </details>
          )}

          {sketch.components.map((c) => {
            const hasRule = sketch.repeats.some((r) => r.componentId === c.id);
            return (
              <div key={c.id} className="rounded-[6px] border border-(--rule) px-2.5 py-2 flex flex-col gap-1.5">
                <p className="text-[11.5px] text-(--fg-primary)">
                  {c.name}
                  <span className="text-(--fg-muted) text-[10px]"> · {c.shapeIds.length} shape(s)</span>
                </p>
                {hasRule ? (
                  <p className="text-[10.5px] text-(--fg-muted)">
                    Repeating. Change the count in the values list above.
                  </p>
                ) : (
                  <>
                    <div className="flex items-center gap-1.5 text-[10.5px]">
                      <label className="text-(--fg-muted)">count</label>
                      <input
                        type="number"
                        min={1}
                        value={repeatCount}
                        onChange={(e) => setRepeatCount(Number(e.target.value))}
                        className="num w-[46px] h-[22px] px-1 text-right rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none"
                      />
                      <label className="text-(--fg-muted)">pitch</label>
                      <input
                        type="number"
                        value={repeatPitch}
                        onChange={(e) => setRepeatPitch(Number(e.target.value))}
                        className="num w-[64px] h-[22px] px-1 text-right rounded-[3px] bg-(--ink-raised) border border-(--rule) outline-none"
                      />
                      <span className="text-(--fg-muted)">mm</span>
                    </div>
                    <div className="flex flex-col gap-0.5 text-[10.5px] text-(--fg-muted)">
                      <label className="inline-flex items-center gap-1.5 cursor-pointer">
                        <input
                          type="radio"
                          checked={spacingMode === "driven"}
                          onChange={() => setSpacingMode("driven")}
                        />
                        keep the pitch fixed — the run grows with the count
                      </label>
                      <label className="inline-flex items-center gap-1.5 cursor-pointer">
                        <input
                          type="radio"
                          checked={spacingMode === "derived"}
                          onChange={() => setSpacingMode("derived")}
                        />
                        keep the overall run fixed — the pitch closes up
                      </label>
                    </div>
                    <Button
                      onClick={() =>
                        makeRepeat({
                          componentId: c.id,
                          count: repeatCount,
                          pitch: repeatPitch,
                          spacingMode,
                          direction: { x: 1, y: 0 },
                        })
                      }
                      icon={Repeat}
                      disabled={repeatPitch <= 0}
                      title={repeatPitch <= 0 ? "Set a pitch greater than zero" : undefined}
                    >
                      Repeat it
                    </Button>
                  </>
                )}
              </div>
            );
          })}
        </Section>
      )}

      {started && (
        <Section title="Step 6 · Publish">
          <input
            value={sketch.meta.name}
            onChange={(e) => setTemplateName(e.target.value)}
            className="h-[26px] px-2 text-[11.5px] rounded-[4px] bg-(--ink-raised) border border-(--rule) outline-none focus:border-(--pen) text-(--fg-primary)"
          />
          <div className="flex items-center gap-1.5">
            <Button onClick={checkReadiness} icon={ClipboardCheck} disabled={busy}>
              {busy ? "Checking…" : "Check it"}
            </Button>
            <Button onClick={publishTemplate} icon={Upload} tone="primary" disabled={!readiness?.ready}>
              Publish
            </Button>
          </div>

          {readiness && (
            <div className="rounded-[6px] border border-(--rule) overflow-hidden">
              {readiness.checks.map((c) => (
                <div key={c.label} className="px-2.5 py-1.5 border-t border-(--rule) first:border-t-0 flex gap-2">
                  <span className="shrink-0 mt-[2px]">
                    {c.status === "pass" ? (
                      <CircleCheck className="w-[12px] h-[12px] text-(--ok)" strokeWidth={2.2} />
                    ) : c.status === "warn" ? (
                      <TriangleAlert className="w-[12px] h-[12px] text-(--warn)" strokeWidth={2.2} />
                    ) : (
                      <CircleX className="w-[12px] h-[12px] text-(--crit)" strokeWidth={2.2} />
                    )}
                  </span>
                  <span className="flex-1 min-w-0">
                    <span className="block text-[11px] text-(--fg-primary)">{c.label}</span>
                    <span className="block text-[10.5px] leading-[1.5] text-(--fg-muted)">{c.detail}</span>
                  </span>
                </div>
              ))}
              {readiness.sweep.length > 0 && (
                <div className="px-2.5 py-1.5 border-t border-(--rule) bg-(--ink-sunken) text-[10.5px] text-(--fg-muted)">
                  {readiness.sweep.filter((s) => s.ok).length} of {readiness.sweep.length} test values
                  re-solved with every declared relationship intact.
                </div>
              )}
            </div>
          )}

          {manifest && (
            <div className="rounded-[6px] border border-(--ok) bg-(--ok-soft) px-2.5 py-2">
              <p className="text-[11.5px] text-(--ok) font-medium">
                {manifest.name} v{manifest.version} published
              </p>
              <p className="text-[10.5px] text-(--fg-secondary) mt-0.5">
                Switch the persona to Run to use it as a project engineer would: {manifest.driving.length}{" "}
                value{manifest.driving.length === 1 ? "" : "s"} to type, {manifest.derived.length} worked
                out for them.
              </p>
            </div>
          )}
        </Section>
      )}
    </PanelBody>
  );
}
