/**
 * UPCE authoring kernel — canonical types.
 *
 * This is the single model the parametric authoring workflow reads and writes.
 * It exists because the previous implementation had two disconnected worlds:
 * a well-tested geometric kernel (predicates, DCEL, Jacobians, SVD, DM) that no
 * UI path ever reached, and a string-matching procedural renderer that the UI
 * actually ran. See PARAMETRIC_WORKFLOW_FAILURE_AUDIT.md.
 *
 * Design rules carried from UPCE-MASTER-1.0:
 *   §6   geometry / topology / design-relationship / engineering-meaning are
 *        four different kinds of knowledge and never share a slot.
 *   §9   design relationships live in a NON-DIRECTIONAL constraint graph.
 *        Scalar arithmetic lives in a DIRECTED parameter DAG. Never mixed.
 *   §20  a parameter always carries a role and a provenance. There are no
 *        anonymous parameters.
 *   §22  a constraint is stored abstractly and compiled to residual rows at
 *        solve time. "Wall", "cell", "span" are NOT constraint kinds.
 */

/** Every assertion in the model can answer "who put me here, and why". */
export type ProvenanceOrigin =
  /** Intrinsic to how the shape was drawn (a rectangle's own right angles). */
  | "geometric-fact"
  /** A detector proposed it; a human pressed Accept. */
  | "inference-accepted"
  /** The author asserted it directly. */
  | "user"
  /** Proposed by the constraint-completion assistant and confirmed. */
  | "completion-assistant"
  /** Came in with a published template. */
  | "template"
  /** Generated by expanding a component instance or a repeat rule. */
  | "component";

export interface Provenance {
  origin: ProvenanceOrigin;
  /** One sentence, in the draftsman's vocabulary. Shown in the inspector. */
  detail: string;
  /** Measured facts that supported the proposal, if it came from a detector. */
  evidence?: string[];
  /** 0..1 at proposal time. Absent for author-asserted assertions. */
  confidence?: number;
  /** GEOM-RP/1 predicate id when a detector produced this. */
  predicate?: string;
  createdAt: number;
}

// ---------------------------------------------------------------------------
// Geometry — points are the only solver variables.
// ---------------------------------------------------------------------------

export interface SketchPoint {
  /** Deterministic; derived from the owning shape id so it survives rebuilds. */
  id: string;
  x: number;
  y: number;
  /** Shapes whose geometry reads this point. Welded points have several. */
  owners: string[];
  construction?: boolean;
}

export interface SketchSegment {
  id: string;
  p1: string;
  p2: string;
  shapeId: string;
  edgeIndex: number;
  construction?: boolean;
}

/**
 * A circle is a centre point plus a rim point. Radius is then just the distance
 * between two points, so the state vector stays homogeneous (points only) and
 * every existing analytical Jacobian applies unchanged. A `horizontal` fact
 * between centre and rim removes the spurious rotational freedom.
 */
export interface SketchCircle {
  id: string;
  center: string;
  rim: string;
  shapeId: string;
}

// ---------------------------------------------------------------------------
// Constraints — the design intent. Non-directional.
// ---------------------------------------------------------------------------

export type ConstraintKind =
  | "fix"               // pin a point in place (the anchor, §18)
  | "coincident"        // two points are one
  | "horizontal"        // segment is horizontal
  | "vertical"          // segment is vertical
  | "parallel"          // two segments
  | "perpendicular"     // two segments
  | "equal_length"      // two segments
  | "point_on_line"     // point lies on a segment's carrier
  | "midpoint"          // point is the midpoint of a segment
  | "symmetric"         // two points mirror about a segment's carrier
  | "distance"          // |p1 p2| = value
  | "distance_x"        // p2.x - p1.x = value
  | "distance_y"        // p2.y - p1.y = value
  | "point_line_distance" // signed normal offset of p3 from segment p1->p2
  | "angle"             // signed angle between two segments, radians
  | "concentric";       // two circles share a centre

export type ConstraintStrength =
  /** Structural truth of the primitive itself. Not deletable in place. */
  | "fact"
  /** Author-asserted design intent. */
  | "hard"
  /** Accepted inference; first to be relaxed when a conflict is resolved. */
  | "soft"
  /** Measurement only. Contributes no residual row and removes no DOF. */
  | "reference";

export type ConstraintState = "active" | "suppressed" | "redundant" | "conflicting";

export interface SketchConstraint {
  id: string;
  kind: ConstraintKind;
  /** Point ids, in the order each kind documents in `residuals.ts`. */
  points: string[];
  /** Segment ids; lowered to their endpoints when residuals are assembled. */
  segments: string[];
  /** Literal target. Ignored when `paramRef` is set. */
  value?: number;
  /** Second literal, used only by `fix` to pin the y coordinate. */
  valueY?: number;
  /**
   * Which side of a directed measurement the target lies on, +1 or -1.
   *
   * `point_line_distance` measures a SIGNED normal offset, so a thickness of
   * 300 mm means one thing on the left face of a loop and the mirror image of
   * it on the right face. Keeping the handedness here lets a single positive
   * parameter drive both faces, which is exactly what "one wall thickness, two
   * walls" requires. Defaults to +1.
   */
  sign?: 1 | -1;
  /** Name of the parameter that drives the target, if any. */
  paramRef?: string;
  /**
   * Multiplier applied to the parameter's value. Repeat expansion uses it so a
   * single `Pitch` parameter can place instance 3 at `3 x Pitch` without
   * inventing three separate parameters. Defaults to 1.
   */
  paramScale?: number;
  strength: ConstraintStrength;
  driving: boolean;
  state: ConstraintState;
  provenance: Provenance;
  /** Plain-language label, e.g. "left and right walls stay equal". */
  label: string;
  /** Set when DOF analysis found this row dependent on the others. */
  diagnostic?: string;
}

// ---------------------------------------------------------------------------
// Parameters — the scalar DAG. Directional.
// ---------------------------------------------------------------------------

export type ParameterRole = "DRIVING" | "DERIVED" | "FIXED" | "MEASURED";
export type ParameterType = "LENGTH" | "ANGLE" | "COUNT" | "RATIO";
export type ParameterUnit = "mm" | "deg" | "count" | "ratio";

export interface SketchParameter {
  /** Unique, and also the identifier used inside expressions. */
  name: string;
  role: ParameterRole;
  type: ParameterType;
  unit: ParameterUnit;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  /** Present if and only if role === 'DERIVED'. */
  expr?: string;
  /** Dependencies extracted from the parsed AST, never by substring. */
  dependencies?: string[];
  provenance: Provenance;
  /** Constraints whose target this parameter drives. */
  boundConstraints: string[];
  /** Exposed to the project-engineer form when the template is published. */
  published: boolean;
  uiGroup?: string;
  description?: string;
}

// ---------------------------------------------------------------------------
// Components and repeats — the generalisation mechanism (§23).
// ---------------------------------------------------------------------------

export interface ComponentPort {
  id: string;
  name: string;
  /** Point that carries the port's origin. */
  pointId: string;
  /** Second point defining the port's direction; optional for point ports. */
  directionPointId?: string;
}

export interface ComponentDefinition {
  id: string;
  name: string;
  /** Shape ids that make up one instance of the unit. */
  shapeIds: string[];
  ports: ComponentPort[];
  createdAt: number;
  /** Local-frame snapshot: the unit's geometry at authoring time. */
  localShapes: unknown[];
}

export type RepeatSpacingMode =
  /** The author fixes the pitch; the extent grows with the count. */
  | "driven"
  /** The author fixes the extent; the pitch is span / count. */
  | "derived";

export interface RepeatRule {
  id: string;
  componentId: string;
  /** Name of the integer parameter holding the count. */
  countParam: string;
  /** Name of the length parameter holding the pitch (driven) or extent (derived). */
  spacingParam: string;
  spacingMode: RepeatSpacingMode;
  /** Unit direction in model space. */
  direction: { x: number; y: number };
  /** Whether consecutive instances weld their touching vertices. */
  weldAdjacent: boolean;
  provenance: Provenance;
}

// ---------------------------------------------------------------------------
// The document.
// ---------------------------------------------------------------------------

export interface AuthoringSketch {
  points: Record<string, SketchPoint>;
  /** Stable ordering; index i owns X[2i], X[2i+1]. */
  pointOrder: string[];
  /**
   * Raw `${shapeId}:v${i}` id -> the welded point that absorbed it. Every raw id
   * appears here, including the ones that were their own host, so lifting never
   * has to guess where a vertex went.
   */
  pointAliases: Record<string, string>;
  segments: Record<string, SketchSegment>;
  circles: Record<string, SketchCircle>;
  constraints: SketchConstraint[];
  parameters: Record<string, SketchParameter>;
  components: ComponentDefinition[];
  repeats: RepeatRule[];
  /**
   * Shapes present in the drawing that carry no constraint-editable primitive
   * (ellipses, splines). Rendered and measured, never advertised as editable.
   */
  carrierShapeIds: string[];
  units: "mm";
  meta: SketchMeta;
}

export interface SketchMeta {
  name: string;
  /**
   * The author has looked at the remaining freedom and declared it intended.
   *
   * §26 of the repair brief: a sketch that is deliberately not rigid must be
   * publishable. Without this flag the readiness check would force every
   * drawing to be fully constrained, which is the dangerous reading the brief
   * warns against.
   */
  freedomIsIntentional: boolean;
  publishedAt?: number;
  /** Bumped on every publish so a user-mode drawing can name its source. */
  version: number;
}

export function emptySketch(): AuthoringSketch {
  return {
    points: {},
    pointOrder: [],
    pointAliases: {},
    segments: {},
    circles: {},
    constraints: [],
    parameters: {},
    components: [],
    repeats: [],
    carrierShapeIds: [],
    units: "mm",
    meta: { name: "Untitled component", freedomIsIntentional: false, version: 0 },
  };
}

// ---------------------------------------------------------------------------
// Candidates — what a detector produces. Never applied without confirmation.
// ---------------------------------------------------------------------------

export type CandidateKind = "constraint" | "parameter" | "derived";

export interface ConstraintCandidate {
  id: string;
  kind: "constraint";
  /** The constraint that would be created verbatim on Accept. */
  constraint: Omit<SketchConstraint, "id">;
  /** What was detected, in one sentence. */
  headline: string;
  /** Measured numbers backing the claim. */
  evidence: string[];
  /** How far the geometry currently is from satisfying it exactly. */
  deviation: string;
  /** What accepting it will preserve under future edits. */
  preserves: string;
  /** DOF this candidate would remove, from the admissibility gate. */
  dofRemoved: number;
  /** Set when the gate found the row already implied by existing constraints. */
  admissible: boolean;
  admissibilityNote?: string;
  confidence: number;
  /** Shape ids to highlight when the card is hovered. */
  affectedShapeIds: string[];
  /**
   * How many further detections this one already accounts for. Set by the
   * minimisation pass so the author sees one card instead of eight duplicates.
   */
  impliedCount?: number;
}

export interface DerivedCandidate {
  id: string;
  kind: "derived";
  /** Parameter that would be created as DERIVED. */
  name: string;
  expr: string;
  value: number;
  headline: string;
  evidence: string[];
  /** Result of the perturbation gate (§49.4). */
  validation: {
    cases: number;
    passed: number;
    maxError: number;
  };
  confidence: number;
  /** Existing DRIVING parameters the expression reads. */
  dependencies: string[];
}

export type Candidate = ConstraintCandidate | DerivedCandidate;
