/**
 * Bundles docs/bridge-formulas/*.txt into lib/bridge/knowledge/corpus.generated.ts
 * so the drafting agent (server side) and the editor can search them without
 * reading files at runtime.
 *
 *   bun run knowledge:build
 *
 * The docs are the source of truth; a test fails if the bundle is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export function readCorpus(root = path.resolve(__dirname, "..")): { file: string; title: string; text: string }[] {
  const dir = path.join(root, "docs", "bridge-formulas");
  return readdirSync(dir)
    .filter((f) => f.endsWith(".txt"))
    .sort()
    .map((file) => {
      const text = readFileSync(path.join(dir, file), "utf8").replace(/\r\n/g, "\n");
      const head = text.split("\n").slice(0, 8).map((l) => l.trim()).filter((l) => l && !/^=+$/.test(l) && l !== "AAGENTO BRIDGE PLATFORM");
      const title = /^(?:Bridge Type|System):\s*(.+)$/m.exec(text)?.[1]?.trim() ?? head[0]?.replace(/^AAGENTO BRIDGE PLATFORM\s*—\s*/, "") ?? file;
      return { file, title, text };
    });
}

export function renderCorpus(docs: ReturnType<typeof readCorpus>): string {
  return `// GENERATED by scripts/build-bridge-knowledge.ts from docs/bridge-formulas — do not edit.\n// Regenerate with: bun run knowledge:build\n\nexport const BRIDGE_DOCS: { file: string; title: string; text: string }[] = ${JSON.stringify(docs, null, 1)};\n`;
}

if (import.meta.main) {
  const out = path.resolve(__dirname, "..", "lib", "bridge", "knowledge", "corpus.generated.ts");
  writeFileSync(out, renderCorpus(readCorpus()));
  console.log(`wrote ${out}`);
}
